
        PRAGMA  6809    ; KJF: Restrict code to using just valid 6809 instructions.

ORGIN   EQU $0989       ; KJF: The code references ORGIN but does not define it, though
                        ;   the assembly listing shows it evaluating to $0989.
STACK   EQU $0400       ; KJF: The code references it but does not define it, though
                        ;   the assembly listing shows it evaluating to $0400.

*****************************************
* I N S T R U C T I O N S   F O R   U S E
*****************************************
*
*
**************************************************************************
* ERROR NUMBERS AND THEIR MEANING
* (THE EQUATES ARE USED SO THAT ERRORS CAN BE RESEARCHED USING XREF LIST)
* DEFINITIONS START WITH BASIC LINE NUMBER 256 IN DOS
**************************************************************************
ERR0    EQU     0       256 NO ERRORS
ERR1    EQU     1       257 I/O ERROR - DRIVE NOT READY
ERR2    EQU     2       258 I/O ERROR - WRITE PROTECTED
ERR3    EQU     3       259 I/O ERROR - WRITE FAULT
ERR4    EQU     4       260 I/O ERROR - SEEK ERROR OR RECORD NOT FOUND
ERRS    EQU     5       261 I/O ERROR - CRC ERROR
ERR6    EQU     6       262 I/O ERROR - LOST DATA
ERR7    EQU     7       263 I/O ERROR - UNDEFINED BIT 1
ERR8    EQU     8       264 I/O ERROR - UNDEFINED BIT 0
ERR9    EQU     9       265 REGISTER ARGUMENT INVALID
ERR10   EQU     10      266 FILE'S DIRECTORY ENTRY NOT FOUND
ERR11   EQU     11      267 DIRECTORY IS FULL
ERR12   EQU     12      268 FILE WAS CREATED BY 'OPEN' FUNCTION
ERR13   EQU     13      269 FILE NOT CLOSED AFTER CHANGES
ERR14   EQU     14      270 ATTEMPTING TO ACCESS AN UNOPENED FILE
ERR15   EQU     15      271 ATTEMPT TO READ - READ PROTECTED
ERR16   EQU     16      272 RBA OVERFLOW (EXCEEDS 3 BYTES - 16,777,216)
ERR17   EQU     17      273 ACCESS BEYOND EOF - EXTENSION NOT ALLOWED
ERRl8   EQU     18      274 FAT REWRITE ERROR
ERR19   EQU     19      275 ATTEMPT TO CLOSE UNOPENED FILE
ERR20   EQU     20      276 CAN"T ACCESS RANDOMLY - REC SIZE IS ZERO!
ERR21   EQU     21      277 ATTEMPT TO WRITE - WRITE PROTECTED
ERR22   EQU     22      278 CAN"T EXTEND FILE - DISK CAPACITY EXCEEDED
ERR23   EQU     23      279 ERROR WHILE LOADING OVERLAY - FUNCTION NOT PERFORMED
ERR24   EQU     24      280 INSUFFICIENT PRINT SPACE ALLOCATED
ERR25   EQU     25      281 I/O ERROR DURING BASIC LINE READ
ERR26   EQU     26      282 PROGRAM'S LOAD ADDRESS IS TOO LOW
ERR27   EQU     27      283 FIRST BYTE OF PROGRAM FILE NOT EQUAL TO ZERO
ERR28   EQU     28      284 SPACE FOR BUFFERED KBD NOT BIG ENOUGH
ERR29   EQU     29      285 NOT ENOUGH MEMORY
ERR30   EQU     30      286 OUTPUT FILE ALREADY EXISTS
ERR31   EQU     31      287 WRONG DISKETTE
*
**************************************************************************
* DISK DATA CONTROL BLOCK (DCB) FORMAT
**************************************************************************
*
* BYTES CONTENTS
* ----- --------
* THESE ITEMS ARE A COPY OF DISK DIRECTORY ENTRY
* 0-7   FILENAME
* 8-10 FILE EXTENSION
* 11    F0=BASIC PGM,1=BASIC DATA,2=MACHINE LANG. PGM,3=TEXT ED. SOURCE)
* 12    ASCII FLAG (0=BINARY, FF = ASCII FILE)
* 13    NUMBER OF FIRST CLUSTER IN FILE
* 14-15 NUMBER OF BYTES IN USE IN LAST SECTOR OF FILE
* THESE ITEMS WERE ADDED, USING LAST 16 BYTES OF DIRECTORY ENTRY
* 16    CURRENT FILE STATUS
*       BIT 0 ON ALLOWS READS
*       BIT 1 ON ALLOWS WRITES
*       BIT 2 ON ALLOWS FILE CREATE IF NON-EXISTANT
*       BIT 3 ON ALLOWS FILE EXTENSION BEYOND EOF ON ACCESS ATTEMPTS
*       BIT 4 ON MEANS WORK FILE - DELETE FILE WHEN CLOSED
*       BIT 5 ON PREVENTS REWRITE OF FAT EVERY TIME A SECTOR IS ADDED TO
*               THE FILE. (MINOR POWER FAILURE INCONSISTANCY COULD RESULT)
*       BIT 6 ON MEANS I/O BUFFER IS SHARED. EACH LOGICAL I/O REQUIRES
*               A PHYSICAL I/O
*       BIT 7 RESERVED FOR FUTURE OPTION(LIKE RELEASE SPACE WHEN FILE SHORTENED)
*       (ALL BITS OFF = FILE CLOSED>
* 17-18 LOGICAL RECORD SIZE CAS OF LAST TIME FILE WAS CLOSED>
*       ZERO MEANS VARIABLE LENGTH WITH RECORDS TERMINATED BY THE
*            DELIMITER STORED BELOW.
*       $FFFF MEANS VARIABLE LENGTH WITH FIRST TWO BYTES OF RECORD
*            CONTAINING SIZE OF THE REST OF THE RECORD.
*       ALL OTHER VALUES MEAN FIXED LENGTH OF SPECIFIED SIZE.
* 19    VARIABLE LENGTH RECORD TERMINATOR
* 20-31 AT PRESENT, UNUSED PART OF DIRECTORY ENTRY - USE WITH CAUTION.
*
* THESE ITEMS ARE USED FOR PHYSICAL I/O PARAMETERS
* 32    LAST I/O OPCD
* 33    LAST I/O DRIVE
* 34    LAST I/O TRACK
* 35    LAST I/O SECTOR
* 36-37 LAST I/O BUFFER POINTER
* 38    LAST I/O RESULT CODE
*
* THESE ITEMS ARE FOR LOGICAL USE
* 39-40 LOGICAL RECORD BUFFER (CAN BE SAME AS DCBBUF IF DCBRSZ=256)
* 41-42 LAST I/O PHYSICAL RECORD NUMBER (EFORE XLATE INTO SECTOR WITHIN
*       GRANULE). THIS IS THE RECORD CURRENTLY IN THE BUFFER.
* 43-45 CURRENT RELATIVE BYTE ADDRESS (RBA) OF FILE DATA POINTER
* 46-47 CURRENT LOGICAL RECORD NUMBER
* 48    MODIFIED DATA TAG - SET NON-ZERO WHEN BUFFER CONTENTS CHANGED
*
* EQUATES FOLLOW FOR MEANINGFUL SOURCE CODE WHEN ACCESSING DCB
* IE: STD DCBLRN,U SAVE NEW LOGICAL RECORD NUMBER
*     (BETTER THAN STD 46,U )
DCBFNM  EQU     0           FILE NAME
DCBFEX  EQU     8           FILE NAME EXTENSION
DCBFTY  EQU     11          FILE TYPE
DCBASC  EQU     12          ASCII CODE
DCBFCL  EQU     13          FIRST CLUSTER NUMBER
DCBNLS  EQU     14          NUMBER OF BYTES USED IN LAST SECTOR
DCBCFS  EQU     16          CURRENT FILE STATUS
DCBRSZ  EQU     17          RECORD SIZE
DCBTRM  EQU     19          VAR LEN RECORD TERMINATOR
DCBMRB  EQU     20          MAX RBA
DCBUSR  EQU     23          USER AREA
DCBOPC  EQU     32          OPERATION CODE
DCBDRV  EQU     33          DRIVE
DCBTRK  EQU     34          TRACK
DCBSEC  EQU     35          SECTOR
DCBBUF  EQU     36          I/O BUFFER ADDRESS
DCBOK   EQU     38          I/O RESULT CODE
DCBLRB  EQU     39          LOGICAL RECORD BUFFER ADDRESS
DCBPRN  EQU     41          PHYSICAL RECORD NUMBER IN BUFFER
DCBRBA  EQU     43          CURRENT RELATIVE BYTE ADDRESS
DCBLRN  EQU     46          CURRENT LOGICAL RECORD NUMBER
DCBMDT  EQU     48          MODIFIED DATA TAG
DCBSZ   EQU     DCBMDT+1    SIZE OF DCB (CURRENTLY 50 BYTES)
*
*****************************************************
* EQUATES TO SUPPORT ROUTINES IN ROM OPERATING SYSTEM
*****************************************************
POLCAT  EQU     $A000
ROLTAB  EQU     $152        KBD ROLLOVER TABLE
JOYIN   EQU     $A00A
BLKIN   EQU     $A006
CSRDON  EQU     $A004
WRTLDR  EQU     $A00C
BLKOUT  EQU     $A008
BLKTYP  EQU     $7C
BLKLEN  EQU     $7D
CBUFAD  EQU     $7E
IRQ     EQU     $10C
POTS    EQU     $15A        JOYSTICK POT VALUES
ALPHLK  EQU     $11A        KBD RTN"S ALPHA LOCK SWITCH
*
******************************
* EQUATES TO XREF USE OF PIA"S
******************************
U4ACR   EQU     $FF21       CONTROL REG
U4ADR   EQU     $FF20       DATA REG
U4ADD   EQU     $FF20       DATA DIRECTION REG
U4BCR   EQU     $FF23
U4BDR   EQU     $FF22
U4BDD   EQU     $FF22
U8ACR   EQU     $FF01
UBADR   EQU     $FF00
U8ADD   EQU     $FF00
U8BCR   EQU     $FF03
U8BDR   EQU     $FF02
U8BDD   EQU     $FF02
*
* MISC ADDITIONAL EQUATES
ENABLE  EQU     %00110101
DSABLE  EQU     %00110100
* COLOR VALUES
BUFF    EQU     %00000000
CYAN    EQU     %01010011
MGNTA   EQU     %10101010
ORANGE  EQU     %11111111
GREEN   EQU     %00000000
YELLOW  EQU     %01010101
BLUE    EQU     %10101010
RED     EQU     %11111111
* CODES RETURNED BY POLCAT FOR FUNCTION KEYS
UP      EQU     $5E     UP ARROW
DOWN    EQU     $0A     DOWN ARROW
RIGHT   EQU     $09     RIGHT ARROW
LEFT    EQU     $08     LEFT ARROW
SUP     EQU     $5F     SHIFT UP ARROW
SDOWN   EQU     $5B     SHIFT DOWN ARROW
SRIGHT  EQU     $5D     SHIFT RIGHT ARROW
SLEFT   EQU     $15     SHIFT LEFT ARROW
BREAK   EQU     $03     BREAK KEY
CLEAR   EQU     $0C     CLEAR KEY
SCLEAR  EQU     $5C     SHIFTED CLEAR
ENTER   EQU     $0D     ENTER KEY
AT      EQU     $40     '@' KEY
SAT     EQU     $13     SHIFTED '@' KEY
*
*******************************************************
* D O S M A C R O A N D L O G I C A L E Q U A T E S
*******************************************************
DOS      MACR   CALL A DOS FUNCTION
    LDA #\2 OPTION
    JSR [\1] INDIRECT FUNCTION ADDR
    ENDM

* SYSTEM Macro added by Keith Frechette.
SYSTEM  MACR    CALL A ROM FUNCTION
        JSR [\1]
        ENDM

*
* EQUATES USED WITH DOS MACRO
*
* THE FOLLOWING USED WITH 'OPEN'
OPEN    EQU     $600                OPEN FUNCTION
CREATE  EQU     4                   ALLOWS FILE CREATION ON OPEN IF NOT FOUND
EXTEND  EQU     8                   ALLOWS EXTENSION OF FILE TO POINT OF ACCESS
INPUT   EQU     1                   USED TO SIGNIFY THAT READS ARE ALLOWED
IN      EQU     1                   SHORTER FORM OF ABOVE
OUT     EQU     2                   ALLOWS WRITES
OUTPUT  EQU     CREATE+EXTEND+OUT   USUAL COMBINATION FOR OUTPUT FILES
WORK    EQU     16                  CAUSES FILE TO BE KILLED WHEN CLOSED <WORK FILE>
FAST    EQU     32                  MINIMIZES FAT REWRITES
SHARE   EQU     64                  USED WHEN 2 OR MORE FILES SHARE THE SAME I/O BUFFER
* EXAMPLES:

* DOS OPEN INPUT                TO READ AN EXISTING FILE
* DOS OPEN OUTPUT               TO CREATE & EXTEND AN OUTPUT FILE
* DOS OPEN IN+OUT               TO UPDATE AN EXISTING FILE <NO EXTENSIONS>
* DOS OPEN INPUT+OUTPUT+WORK    TO CREATE, EXTEND, READ & WRITE AND KILL
*                               WHEN CLOSED <A WORK FILE>
* 'SHARE' CAN BE ADDED TO ANY OF THE ABOVE EXAMPLES IF 2 OR MORE FILES
* WILL BE USING THE SAME I/O BUFFER AT THE SAME TIME. THIS OPTION CAUSES
* A PHYSICAL I/O TO REFRESH THE BUFFER WITH EVERY LOGICAL I/O OPERATION.
* WITHOUT THIS OPTIONt SEVERAL LOGICAL READS OR WRITES TO OR FROM THE
* SAME PHYSICAL SECTOR CAN BE DONE WITH A SINGLE PHYSICAL I/O. 'SHARE'
* INCREASES THE AMOUNT OF ACTUAL I/O ACTIVITY, BUT ALLOWS USE OF MANY
* FILES AT THE SAME TIME WITH MUCH LESS MEMORY REQUIREMENTS FOR BUFFERS.
*
** USED WITH 'CLOSE' FUNCTION
CLOSE   EQU     $602      CLOSE A FILE OPTIONS NOT USED
IT      EQU    0
* EXAMPLE:
* DOS CLOSE, IT    TO CLOSE A FILE
*
* USED WITH 'READ' AND 'WRITE' FUNCTIONS
READ    EQU     $604    READ A RECORD
WRITE   EQU     $606    WRITE A RECORD
RBA     EQU     1       TO READ USING REL BYTE ADDR
RECORD  EQU     0
REC     EQU     0
UPDATE  EQU     2       TO PREVENT ADVANCING REC NBR OR RBA AFTER A READ
NOW     EQU     8       1 = ENSURE I/O BUFFER IS WRITTEN TO DISK AFTER LOGICAL WRITE
* EXAMPLES:
* DOS READ,RECORD       TO RANDOMLY READ BY RECORD NUMBER
*                       (FIXED LENGTH RECS ONLY)
*                       (USE THIS FOR NORMAL SEQUENTIAL READ OF FIXED LENGTH)
* DOS READ.RBA          TO READ THE RECORD POINTED AT BY RBA
*                       (REQUIRED IF USING VARIABLE LENGTH RECORDS>
* DOS READ,UPDATE       TO READ BY REC NBR WITHOUT ADVANCING REC NSR
* DOS READ,RBA+UPDATE   TO READ THE RECORD POINTED AT BY RBA & NOT CHANGE RBA
* DOS WRITE,REC         WRITE VIA RECORD NUMBER <FIXED LENGTH ONLY>
* DOS WRITE,RBA         WRITE FIXED OR VARIABLE RECORD
* DOS WRITE,UPDATE      UNLIKELY OPTION - WRITES RECORD BUT DOES NOT CHANGE
*                       RBA OR REC NUMBER. COULD BE REWRITTEN AGAIN.
* DOS WRITE,RBA+NOW     SAME AS: DOS WRITE,RBA FOLLOWED BY DOS RELSE,IT
*
RELSE   EQU     $608    USE TO RELEASE I/O BUFFER WITHOUT CLOSING FILE
* IF CONTENTS OF BUFFER HAVE BEEN CHANGED, IT IS REWRITTEN. THEN DCBPRN
* IS SET TO $FFFF TO ENSURE A PHYSICAL I/O BEFORE THE NEXT LOGICAL I/O.
* USE THIS FUNCTION WHEN USER IS CONTROLLING A SHARED BUFFER.
* EXAMPLE:
* DOS RELSE, IT
*
* USED WITH OVERLAYABLE FUNCTIONS
DO      EQU     $60A    USE TO LOAD IF NECESSARY, THEN EXECUTE AN OVERLAY
GO      EQU     $60C    USE TO XFER CONTROL FROM ONE OVERLAY TO ANOTHER IN SAME AREA
LOAD    EQU     $60E    USE TO LOAD A SYSTEM OVERLAY - IT IS LOADED AT THE
* EXAMPLE:
* DOS DO,MAP
*
* THE FOLLOWING USED WITH "LOAD" AND "DO" FUNCTIONS
INIT    EQU     1       INITIALIZATION OF DOS
* EXAMPLE:
* DOS DO,INIT EXIT PROGRAM & RE-INITIALIZE DOS
* NOTE: STACK AND OLYLOC SHOULD BE RESET BEFORE USING THIS OVERLAY
*
MENU    EQU     14      DISPLAY DOS MAIN MENU
* EXAMPLE:
* LDS #STACK
* LDD #OVRLAY WHERE OVERLAY AREA SHOULD START
* STD >OLYLOC
* DOS DO,MENU
*
MAP     EQU     10      DISPLAY BASIC LINES
* EXAMPLE:
* LDD #280 FIRST LINE NUMBER TO BE DISPLAYED
* LDY #283 LAST LINE TO BE DISPLAYED
* LDU <CURSOR STARTING DISPLAY ADDRESS
*    (IF STARTING ADDR IS ZERO, SCREEN WILL BE CLEARED FIRST AND ROUTINE
*     WILL EXIT WITH U->FIRST CHAR AFTER FIRST LEFT BRACKET ON SCREEN)
* PSHS D,Y,U (PARAMETERS ARE PASSED IN THE STACK)
* DOS DO,BASMSG
* PULS D,Y,U NORMALIZE STACK
* BNE ERROR BRANCH ON ANY FAILURE IF DESIRED
*
RUNIP   EQU     2       KEYIN A NAME AND RUN PGM
* EXAMPLE:
* DOS DO.RUNIP
*
CPYFLE  EQU     5       GET INFO FROM USER & COPY A FILE
* EXAMPLE:
* DOS DO,CPYFLE (IF "GO" USED, DOS MENU FOLLOWS COPY FUNCTION)
*
FIELDI  EQU     11      INPUT A MAPPED FIELD
* EXAMPLE:
* LDX DEST WHERE THE DATA GOES IN MEMORY
* LDU FLDADR POINT TO FIELD ON SCREEN
* DOS DO.FIELDI INPUTS THE FIELD
* B IS RETURNED CONTAINING LAST KEYSTROKE ENTERED
*
EXEC    EQU     12      GIVEN USRDCB CONTENTS, LOAD ROOT & EXECUTE PROGRAM
* EXAMPLE:
* (WHATEVER LOGIC TO PUT NAME IN DCB AT *USRDCB*)
* DOS GO,EXEC JUMP TO LOAD & EXECUTE OVERLAY
*
REALTM  EQU     13      CLOCK DISPLAY OVERLAY (SEE SKEL FOR EXAMPLE OF USE)
*
BUFPRT  EQU     15      BUFFERED PRINT OVERLAY
* EXAMPLE:
*   LDU #SIZE (TOTAL MEMORY TO BE USED (ROUTINE + BUFFER)
*             (ROUTINE IS ABOUT 220 BYTES)
*   DOS DO, BUFPRT (SETS IT UP - OVERLAY & BUFFER PROTECTED FROM
*                  BEING OVERLAYED).
* FROM THIS POINT ON, CHARACTERS PRINTED BY CALLING *PRNT* WILL GO
* THROUGH BUFFERED I/O. TO WRAP UP AT EOJ, DO THIS:
*   CLRA
*   JSR [PRNT] REQUEST TO END BUFFERING.
* THIS WILL CAUSE 'PRNT' TO WAIT UNTIL THE BUFFER IS EMPTIED (PRINTER
* AS CAUGHT UP), AND THEN OVERLAY AND BUFFER AREA ARE RELEASED.
*
COPY    EQU     17      COPY A FILE
* GIVEN:
* U->SOURCE FILE DCB (NOT OPENED)
* Y->DEST FILE DCB (NOT OPENED)
* B (BIT 0) - OFF IF NO DISKETTE SWAPPING, ON FOR DISKETTE SWAPPING
* RETURNED A=ERROR NUMBER
*
* SIMILAR FUNCTIONS FOR USING USER OVERLAYS
DOUSR   EQU     $610     LOAD IF NECESSARY & EXECUTE USER OVERLAY
GOUSR   EQU     $612     JUMP TO A DIFFERENT OVERLAY
LODUSR  EQU     $614     LOAD USER OVERLAY
* USER SHOULD PROVIDE EQUATES FOR HIS OVERLAYS HERE

ERROR   EQU     $616     JSR HERE FOR DISPLAY OF ERR MSG
*
TIME    EQU     $618          TURN ON/OFF TIME ROUTINE
ON      EQU     1
OFF     EQU     0
* EXAMPLE•
* LDU #TMERTN LOAD ADDR OF ROUTINE
* DOS TIME,ON GO ACTIVATE THIS ROUTINE
*
PRNT    EQU     $61A     PRINT A CHARACTER ON PRINTER
* THIS IS CHANGED BY CALLING BUFFERED PRINTER OVERLAY TO POINT
* AT BUFFERED IO ROUTINE
*
KEYIN   EQU     $61C     POLL KEYBOARD FOR INPUT CHARACTER
* THIS IS CHANGED BY CALLING BUFFERED KEYBOARD OVERLAY TO POINT
* AT BUFFERED IO ROUTINE
*
BASIC   EQU     $61E     JMP HERE TO RETURN TO BASIC
*
*****************************************************
* O T H E R   U S E F U L   M A C R O S   F O L L O W
*****************************************************
ENABLI  MACR            ENABLE INTERUPTS
        ANDCC #%11101111
        ENDM
*
DSABLI  MACR            DISABLE INTERUPTS
        ORCC #%01010000
        ENDM
*
NEGD    MACR            NEGATE D
        COMA
        COMB
        ADDD #1
        ENDM
*
LSRD    MACR            LOGICAL SHIFT RIGHT D
        LSRA
        RORB
        ENDM
*
LSLD    MACR            LOGICAL SHIFT LEFT D
        LSLB
        ROLA
        ENDM
*
CLRD    MACR            CLEAR D
        CLRA
        CLRB
        ENDM
*
INCD    MACR            ADD 1 TO D
        ADDD #1
        ENDM
*
******************************************************************
* S Y S T E M   R A M    -   D O S
******************************************************************
* ADDITIONAL WS USING EXTENDED ADDRESSING
        ORG     $15E
        ORG     $600
* AREA WHERE USER ACCESSABLE VECTORS & VARIABLES STORED
VECTOR  RMB     2*16     2 BYTES PER VECTOR
* OPEN OPEN A DISK FILE
* CLOSE CLOSE A DISK FILE
* READ READ FROM A DISK FILE
* WRITE WRITE TO A DISK FILE
* RELSE RELEASE I/O BUFFER <ALLOW USE FOR ANOTHER FILE)
* DO LOAD & EXECUTE A SYSTEM OVERLAY
* GO LOAD ON TOP OF CURRENT OVERLAY & JUMP TO SYSTEM OVERLAY
* LOAD LOAD SYSTEM OVERLAY
* DOUSR LOAD & EXECUTE USER OVERLAY
* GOUSR LOAD ON TOP OF CURRENT OVERLAY & JUMP TO USER OVERLAY
* LODUSR LOAD USER OVERLAY
* ERROR DISPLAY ERROR NUMBER IN *A*
* TIME TURN ON/OFF TIME INTERVAL ROUTINE
* PRNT PRINT A CHARACTER ON PRINTER
* KEYIN INPUT NEXT KEYSTROKE FROM KEYBOARD
* BASIC RETURN TO BASIC CONTROL
CLOCK   RMB     2       COUNT OF 60THS OF A SECOND
RETRYS  RMB     1       NUMBER OF I/O RETRYS INITIALLY SET TO 5
RATE    RMB     2       TIME CONSTANT THAT CONTROLS PRINTER TRANSMISSION SPEED
OLYLOC  RMB     2       ADDRESS WHERE CURRENT OVERLAY WAS LOADED
USRBSE  RMB     2       BASE OF USER'S ROOT + 1. POINTS TO ENTRY ZERO OF OVERLAY'S RBA
HOOK1   RMB     2       JUST BEFORE CHECKING FOR AUTO EXECUTE
HOOK2   RMB     2       JUST BEFORE BRANCHING TO USER PROGRAM
HOOK3   RMB     2
HOOK4   RMB     2
HOOKS   RMB     2
RETURN  RMB     2       CONTAINS TWO RTS CODES - ALL HOOKS RETURN THRU HERE
DOSDCB  RMB     DCBSZ   DCB USED TO READ SYSTEM OVERLAYS
MSGDCB  RMB     DCBSZ   DCB USED TO READ "MAPS" AND MESSAGES
USRDCB  RMB     DCBSZ   DCB USED TO READ USER'S PROGRAM & OVERLAYS
SYSBUF  RMB     256     BUFFER FOR SYSTEM USE(DIRECTORY + FAT READS & WRITES>
FATSZ   EQU     69      FILE ALLOCATION TABLE <FAT> SIZE
FAT0    RMB     FATSZ   SAVE AREA FOR DRIVE 0 FAT TABLE
FAT1    RMB     FATSZ   SAME FOR DRIVE 1
FAT2    RMB     FATSZ
FAT3    RMB     FATSZ
FATS    EQU     FAT0
MAXMEM  RMB     2       ADDR OF HIGHEST USEABLE MEMORY
DRIVES  RMB     1       MAX NBR OF DRIVES TO SEARCH ON GLOBAL OPEN
        OPT     L
ENDWSE  RMB     1       END OF EXTENDED WS
        OPT     NOL
*************************************************************************
*   D O S      S T A R T S          H E R E
*************************************************************************
        ORG     ORGIN   SEE lST MODULE FOR VALUE ASSIGNED
        OPT     L
        TTL     DOS - I/O ROUTINES
        OPT     NOL
**************************************************************************
*        O P E N   D I S K   F I L E
*
* GIVEN:
* A=DESIRED FILE STATUS
* U->DCB
* DCBDRV,U = DRIVE TO BE CHECKED ($FF=CHECK ALL DRIVES)
*
* BEFORE CALLING "OPEN", DCB SHOULD CONTAIN: FILENAME, EXTENSION,
* I/O BUFFER ADDRESS. NAME AND EXTENSION ONLY ARE COMPARED
* TO DIRECTORY ENTRIES TO FIND MATCH. TYPE AND ASCII FLAG ARE USED ONLY
* WHEN CREATING FILE (OTHERWISE THEY ARE OVERLAYED BY EXISTING VALUES).
* ALL I/O NEEDED TO OPEN FILE USES THE 2S6 BYTE AREA POINTED TO BY
* LAST I/O ADDRESS AS A BUFFER.
*
* OPEN WORKS EXACTLY THE SAME FOR INPUT OR OUTPUT! ACTION IS CONTROLLED
* BY FILE STATUS SUPPLIED IN "A" (SEE DCBCFS IN DCB DESCRIPTION).
*
* OPENING A NON-EXISTANT FILE - IF CREATION IS ALLOWED, FIRST 32 BYTES OF
* DCB ARE PLACED IN DIRECTORY EXCEPT THAT DCBFCL IS SET TO $FF, DCBNLS
* IS SET TO ZERO AND DCBCFS IS SET TO PROVIDED STATUS.
*
* OPENING AN EXISTING FILE - THE 32 BYTE DIRECTORY ENTRY OVERLAYS THE
* FIRST 32 BYTES OF THE DCB EXCEPT FOR DCBCFS WHICH IS SET TO THE PROVIDED
* VALUE.
*
* WHEN FILE IS OPENED• DCBPRN IS SET TO $FFFF (AN INVALID VALUE). DCBRBA
* IS SET TO ZERO, AND DCBLRN IS SET TO ZERO. AT ANYTIME BEFORE OR AFTER
* CALLING OPEN, DCBLRB CAN BE SET OR CHANGED.
*
* FILE TYPE AND ASCII FLAG CAN BE CHANGED AFTER OPEN TO CAUSE THEM TO BE
* CHANGED WHEN FILE IS CLOSED.
*
**************************************************************************
DOPEN   LDB     DCBDRV,U
        PSHS    D,X
        CMPB    #$FF        REQUEST FOR SCAN OF ALL DRIVES
        BEQ     DO0         IF YES
        CMPB    #4          VALID DRIVE REQUESTED?
        BCS     DO1         IF YES
        LDA     #ERR9       PARAMETER ERROR
DOERR   STA     ,S
        PULS    D,X,PC      RETURN WITH ERROR CONDITION
DO0     CLRB                START WITH DRIVE ZERO
DO1     STB     DCBDRV,U
        CLRA                SAY LOOK FOR MATCH
        LBSR    CHKDIR      CHECK DIRECTORY ON THIS DRIVE FOR MATCH
        BEQ     DO5         IF MATCH FOUND
        BMI     DO3         IF NO I/O ERRORS - JUST DIDNT FIND IT
* IT WAS SOME KIND OF I/O ERROR
        CMPA    #1          DRIVE NOT READY?
        BNE     DOERR       IF NO
        TST     1,S         REQUEST FOR SPECIFIC DRIVE?
        BPL     DOERR       IF YES, THEN THIS IS AN ERROR
DO3     TST     1,S         REQUEST FOR SPECIFIC DRIVE?
        BPL     DO4         IF YES, I DIDNT FIND HIS FILE
        LDB     DCBDRV,U    LAST DRIVE CHECKED
        INCB
        CMPB    DRIVES      ANOTHER VALID DRIVE TO CHECK?
        BCS     DO1         IF YES
* MATCH NOT FOUND - IS IT OK TO CREATE?
DO4     LDA   ,S       (DESIRED STATUS)
        BITA   #CREATE CREATE BIT ON?
        BNE    DO4A      IF YES
        LDA    #ERR10   FILE DIRECTORY ENTRY NOT FOUND
        BRA    DOERR
DO4A    TST    1,S      ANY DRIVE SPECIFIED?
        BPL    DO4B     IF SPECIFIC
        CLR    DCBDRV,U CREATE ON DRIVE ZERO
DO4B    LDA    #$FF     SAY LOOK FOR OPEN SLOT
        LBSR   CHKDIR   SCAN THE DIRECTORY
        BEQ    DO4C     IF SLOT FOUND
        BPL    DOERR    IF SOME KIND OF I/O ERROR
        LDA    #ERR11   DIRECTORY IS FULL
DOERRL  BRA    DOERR
DO4C    LDA    ,S       DESIRED STATUS
        STA    1,S      SAVE IT
        LDA    #ERR12   SAY DIRECTORY WAS CREATED
        STA    ,S
        LDA    #$FF
        STA    DCBFCL,U SET NUMBER OF 1ST CLUSTER
        CLRD
        STD    DCBNLS,U CLEAR BYTES IN LAST SECTOR
        STD    DCBMRB,U CLEAR MAX RBA
        STA    DCBMRB+2,U
        LBSR   DCBDIR   XFER DATA TO DIRECTORY
        BRA    DO6      GO CONTINUE PROCESSING
* DIRECTORY ENTRY FOUND
DO5     LDA    ,S       DESIRED STATUS
        STA    1,S      SAVE IT
        CLR    ,S
        LDA    DCBCFS,X CHK PREVIOUS FILE STATUS
        BEQ    DO6       IF IT WAS CLOSED
        ANDA   #CREATE+EXTEND+OUT IF LAST OPENED TO MODIFICATION?
        BEQ    DO6       IF NO
        TST    DCBCFS,X CHK PREVIOUS FILE STATUS
        BEQ    DO6       IF IT WAS CLOSED
        LDA    #ERR13    SAY IT WASNT PREVIOUSLY CLOSED
        STA    ,S
* XFER DIRECTORY ENTRY TO DCB
DO6     LDA    1,S       DESIRED STATUS
        STA    DCBCFS,X PUT IN DIRECTORY ENTRY
        LBSR   DIRDCB    XFER DIRECTORY ENTRY TO DCB
        LDA    DCBCFS,U
        ANDA   #CREATE+EXTEND+OUT WRITES ALLOWED?
        BEQ    DO6A      IF NO
        LBSR   SYSWRT    REWRITE DIRECTORY RECORD
        BNE    DOERRL    IF I/O ERROR
DO6A    LDA    #2
        STA    DCBSEC,U
        LBSR   SYSRED    READ FAT RECORD
        BNE    DOERRL
        LBSR   ADRFAT    POINT "X" AT FAT TABLE IN MEMORY
        PSHS   U
        LDU    #SYSBUF   POINT TO BUFFER
        LDB    #69       BYTES TO MOVE
        LBSR   XFRUX     MOVE THEM
        PULS   U
* DO OPEN RESETTING
        LDD    #$FFFF
        STD    DCBPRN,U
        CLRD
        STD    DCBRBA,U
        STA    DCBRBA+2,U
        STD    DCBLRN,U
        CLR    DCBMDT,U
        LBRA   DC5
*
**************************************************************************
* C L O S E    D I S K   F I L E
*
* GIVEN: U -> DCB (CONTAINING FILE STATUS)
*
* FUNCTION:
* FIND DIRECTORY ENTRY AND VERIFY THAT FILE IS OPEN. THEN, IF FILE IS
* TO BE KEPT, UPDATE AND RE-WRITE DIRECTORY ENTRY AND REWRITE FAT TABLE.
* IF FILE IS TO BE PURGED, MARK DIRECTORY ENTRY AS RE-USEABLE AND RE-WRITE
* THEN MARK CLUSTERS AVAILABLE IN FAT TABLE AND REWRITE.
**************************************************************************
DCLOSE  CLRA            (RESULT CODE)
        PSHS   D,X
        CLRA            SAY LOOK FOR A MATCH
        LBSR   CHKDIR   CHECK DIRECTORY FOR A MATCH
        BEQ    DC1      IF MATCH FOUND
        BPL    DCERR    IF I/O ERR
        LDA    #ERR10   DIRECTORY ENTRY NOT FOUND
DCERR   LBRA   DOERR
DC1     LDA    DCBCFS,U IS FILE OPEN?
        BNE    DC2
        LDA    #ERR19   CLOSING UNOPENED FILE
        BRA    DCERR
DC2     LDD    DCBTRK,U
        PSHS   D        SAVE LOC OF DIR ENT
        LBSR   REWRTE   REWRITE BUFFER IF IT HAD BEEN MODIFIED
        PULS   D
        BNE    DCERR    IF I/O ERROR OCCURRED IN THE PROCESS
        STD    DCBTRK,U RESTORE LOC OF DIR ENT
        LDA    DCBCFS,U
        PSHS   A        SAVE FOR DIRECTORY RE-WRITE DECISION
        CLR    DCBCFS,U CLEAR CUR FILE STATUS IN DCB
        ANDA   #WORK    WORK FILE TO BE DELETED?
        BEQ    DC4      IF NO GO REWRITE DIRECTORY & FAT TABLE
        CLR    ,U       MARK DIRECTORY ENTRY AS RE-USEABLE
        PSHS   X        SAVE ADDR OF DIRECTORY ENTRY
* MARK FAT TABLE ENTRIES AS AVAILABLE
        LBSR   ADRFAT   POINT "X" AT FAT TABLE IN MEM
        LDA    DCBFCL,U GET FIRST CLUSTER NUMBER
        BMI    DC3A     IF NO CLUSTERS IN USE
DC3     LDB    A,X      GET NUMBER OF NEXT CLUSTER
        CLR    A,X      CLEAR CLUSTER ENTRY
        DEC    A,X      SET TO $FF
        TFR    B,A
        TSTA
        BPL    DC3      IF MORE TO GO
DC3A    PULS   X        ADDR OF DIR ENTRY
DC4     LBSR   DCBDIR   XFER TO DIRECTORY
        PULS   A        PRE-CLOSE CFS
        ANDA   #CREATE+EXTEND+OUT WRITES ALLOWED?
        BEQ    DC4B
* SET DCBNLS TO REFLECT DCBMRB (MAX RSB)
        CLRA
        LDB    DCBMRB+2,X
        BNE    DC4A
        LDD    DCBMRB,X IS IT A NULL FILE
        BEQ    DC4A     IF YES
        LDD    #$100
DC4A    STD    DCBNLS,X
        LBSR   SYSWRT   RE-WRITE DIRECTORY RECORD
        BNE    DCERR    IF I/O ERROR
DC4B    LBSR   ADRFAT
        PSHS   U        SAVE DCB ADDR
        LDU    #SYSBUF POINT TO SYSTEM'S BUFFER
        LDB    #69
        LBSR   XFRXU    XFER INTO BUFFER
        LEAX   1,U
        LDB    #256-69-1
        LBSR   XFRUX    CLEAR REST OF BUFFER TO $FF
        PULS   U        RESTORE DCB ADDR
        LDA    #2
        STA    DCBSEC,U
        LBSR   SYSWRT   WRITE IT
        BEQ    DC5
        STA    ,S       IF I/O ERROR
DC5     TST    ,S       SET COND CODES
        PULS   D,X,PC
*
*************************************************************************
* R E A D   A   L O G I C A L   D I S K   R E C 0 R D
*
* GIVEN: U ->DCB (THAT HAS ALREADY BEEN OPENED!)
*        A = FUNCTION DESIRED CODED AS FOLLOWS:
* BIT 0 ON TO READ VIA RBA
*       OFF TO READ VIA LRN
* BIT 1 ON TO READ WITHOUT CHANGING POINTER
*       OFF TO EXIT AFTER POINTING AT NEXT (PREVIOUS) RECORD
* BIT 2 ON TO READ BACKWARDS
*       OFF TO READ FORWARD
* EXAMPLE: A=ZERO TO READ THE CURRENT LOGICAL RECORD AND THEN ADVANCE
* THE LOGICAL RECORD NUMBER BY 1. A = 2 TO 'READ FOR UPDATE" A LOGICAL
* RECORD. A = 1+4 (5) TO READ STARTING WITH THE RBA'TH BYTE OF DATA
* IN THE FILE• FOR DCBRSZ BYTES. THEN SET RBA TO POINT DCBRSZ BYTES
* AHEAD OF THE FIRST BYTE READ.
*
* NOTE: LOGICAL RECORD SIZE, RECORD STORAGE ADDRESS AND I/O BUFFER
* ADDRESS ARE USED. IF LOGICAL RECORD SIZE IS 256, RECORD STORAGE
* AND I/O BUFFER MAY BE THE SAME ADDRESS. IF DCBRSZ IS ZERO, READS WILL
* TRANSFER BYTES FROM THE FILE TO [DCBREC] UNTIL A CHARACTER MATCHING
* DCBTRM IS TRANSFERRED.
**************************************************************************
DREAD PSHS    A,X,Y
        LDD    #$0100+ERR15
        LBSR   RDWR     DO SETUP COMMON TO READ AND WRITE
*
* LOOP TO XFER BYTES TO RECORD AREA
* (X->BUFFER, Y->RECORD AREA)
DR5     LDB    DCBRBA+2,U DISPLACEMENT IN CURRENT SECTOR
        CLRA
        LDA    D,X      GET A BYTE
        STA    ,Y+      STORE IN REAORD AREA
        INC    DCBRBA+2,U ADVANCE POINTER IN BUFFER
        BNE    DR5B     IF IN SAME SECTOR
        LBSR   REWRTE   ENSURE PREVIOUSLY MODIFIED DATA GETS WRITTEN
        BNE    DR5AA    IF WRITE ERR
        LDD    DCBRBA,U
        ADDD   #1       POINT TO NEXT SECTOR
        STD    DCBRBA,U
        LBSR   CALSEC   RECALCULATE TRACK & SECTOR
        BEQ    DR5A     IF OK
DR5AA   LEAS   7,S      SCRAP STUFF IN STACK
        STA    ,S
        PULS   A,X,Y,PC
DR5A    LBSR     DSKRED
        BNE    DR5AA    IF I/O ERROR
DR5B    LDD     ,S       GET AOUNT DOWN VALUE
        BEQ    DR5C     IF VARIABLE LENGTH STRING
        SUBD   #1
        STD    ,S
        BNE    DR5      GO GET ANOTHER CHR
        BRA    RDWRX    GO DO CLEAN-UP COMMON TO READ AND WRITE
DR5C    LDA     DCBTRM,U STRING DELIMITER
        CMPA   -1,Y     WAS LAST AHR STORED A DELIMITER?
        BNE    DR5      IF NO, KEEP GOING
*
***********************************
* CLEAN UP COMMON TO READ AND WRITE
***********************************
* RECORD HAS BEEN READ - CLEAN UP
RDWRX   PULS    D
        LDA    DCBCFS,U FILE STATUS
        BITA   #SHARE   OPTION SET?
        BEQ    DR6A     IF NO
DR6AA   LBSR     REWRTE   FREE UP BUFFER
        LDD    #$FFFF   MARK INVALID SEATOR IN BUFFER
        BRA    DR6B
DR6A    LDA 5,S R/W OPTION
        BITA   #NOW     REWRITE NOW?
        BNE    DR6AA    IF YES
        LDD    DCBRBA,U LAST SEATOR ACCESSED
DR6B    STD    DCBPRN,U MARK WHIAH SEATOR IS NOW IN BUFFER
* CHECK FOR NEW DCBMRB
        LDD    DCBRBA,U
        CMPD   DCBMRB,U
        BCS    DR6D     IF IN A LOWER SECTOR
        BNE    DR6C     IF A HIGHER SECTOR
        LDA    DCBRBA+2,U
        CMPA   DCBMRB+2,U
        BCS    DR6D     IF A LOWER BYTE
DR6C    LDD    DCBRBA,U
        STD    DCBMRB,U
        LDA    DCBRBA+2,U
        STA    DCBMRB+2,U
DR6D    LDA    5,S      READ/WRITE OPTION
        ANDA   #UPDATE SHOULD RBA & LRN BE RESET TO STARTING VALUE?
        PULS   A,X,Y
        BEQ    DR6E     IF NO
* RESTORE ORIGINAL POINTERS
        STA    DCBRBA+2,U
        STX    DCBRBA,U
        STY    DCBLRN,U
DR6E    CLR    ,S
        PULS   A,X,Y,PC
*
***********************************
* SETUP FOR READ OR WRITE
* GIVEN: A=l FOR READ, 2 FOR WRITE
*        B=ERR NBR FOR POSSIBLE USE
***********************************
RDWR   PSHS   D        SAVE IN CASE NEEDED
* IS FILE OPEN?
       LDA    DCBCFS,U
       BNE    RDWRl    IF YES
       LDA    #ERR14   IF NOT OPEN
RDWRER LEAS   4,S      (DIDN' T NEED IT AND RET ADDR)
       STA    ,S
       PULS   A,X,Y,PC
*IS THIS TYPE OF OPERATION ALLOWED (READ OR WRITE)?
RDWRl BITA    ,S      (1 FOR READ, 2 FOR WRITE)
       BNE    RDWR2   IF YES
       LDA    1,S     (ERROR NUMBER PROVIDED)
       BRA    RDWRER
*
* CHECK FOR,STARTING RBA
* IS I/O BY RBA OR LOGICAL RECORD?
RDWR2  LDA    4,S      OPTION PROVIDED
       ANDA   #RBA
       BNE    RDWR4           IF READ VIA RBA, USE RBA'S CURRENT CONTENTS
* READ BY RECORD NUMBER
       LDD    DCBRSZ,U        FIXED OR VARIABLE LENGTH REAOR,S?
       BNE    RDWR3           IF FIXED LENGTH
       LDA    #ERR20          CANT CALCULATE - RSZ = ZERO
       BRA    RDWRER
RDWR3 LBSR    CALRBA          CALCULATE RECORD'S STARTING RBA
       BNE    RDWRER          IF OVERFLOW OCCURRED
*
       OPT    L
* MAKE SURE,STARTING RECORD IS IN BUFFER
RDWR4 LDD     DCBRBA,U        (RELATIVE REAORD NEEDED)
       CMPD   DCBPRN,U        IS NEEDED REAORD IN BUFFER?
       BEQ    RDWR4A          IF Y,S
       LBSR   REWRTE          REWRITE BUFFER IF IT H,S BEEN MODIFIED
       BNE    RDWRER          IF I/O ERROR IN THE PROA,SS
       LBSR   CALSEC          CALCULATE TRACK &,SECTOR
       BNE    RDWRER          IF TRYING TO GO BEYOND EOF
       LBSR   DSKRED          READ THE SECTOR
       BNE    RDWRER          IF I/O ERR
       BRA RDWR5
RDWR4A LBSR   CSENT           CHECK FOR EOF
       BNE    RDWRER          IF TRYING TO GO PAST EOF
*
* CORRECT STARTING SECTOR IS IN BUFFER
* GET SET TO XFER RECORD
RDWR5 PULS    D,Y             (D=l/0, ERR NBR, Y RETURN ADDRl
       OPT    NOL
       LDX    DCBLRN,U
       PSHS   X        SAVE IN A,SE POINTE,S DON'T ADVANCE
       LEAX   1,X      POINT TO NEXT REAORD
       STX    DCBLRN,U
       LDX    DCBRBA,U
       LDA    DCBRBA+2,U
       PSHS   A,X      SAVE INCASE POINTERS DON'T ADVANCE
       LDD    DCBRSZ,U GET RECORD LENGTH
       PSHS   D        SAVE AS COUNT DOWN VALUE FOR LOOP
       PSHS   Y        SAVE RET ADDR
       LDX    DCBBUF,U ADDR OF BUFFER
       LDY    DCBLRB,U ADDR OF LOGIAAL REAORD BUFFER
       RTS             RETURN TO READ OR WRITE LOOP
*
*************************************************************************
* W R I T E   A   L O G I A C L   D I S K    R E C 0 R D
*
* GIVEN: U -> DCB (THAT H,S ALREADY BEEN OPENED!)
*        A = FUNATION D,SIRED AODED ,S FOLLO,S:
* BIT 0 ON TO WRITE VIA RBA
*       OFF TO WRITE VIA LRN
* BIT 1 ON TO WRITE WITHOUT CHANGING POINTER
*       OFF TO EXIT AFTER POINTING AT NEXT (PREVIOUS) REAORD
* BIT 2 ON TO WRITE BACKWARDS
*       OFF TO WRITE FORWARD
* BIT 3 ON TO RELEASE BUFFER AFTER WRITE
*       OFF TO WAIT UNTIL PHYSICAL I/O IS NECESSARY
* NOTE: FUNCTION IS NEARLY THE SAME AS DREAD - SEE NOTES UNDER DREAD.
**************************************************************************
DWRITE PSHS   A,X,Y
       LDD    #$0200+ERR21
       BSR    RDWR     DO SETUP COMMON TO READ AND WRITE
*
* LOOP TO XFER BYTES FROM RECORD AREA
* (X->BUFFER, Y->RECORD AREA)
DW5    LDB    DCBRBA+2,U DISPLACEMENT IN CURRENT,SECTOR
       CLRA
       LDX    DCBBUF,U ADDR OF BUFFER
       LEAX   D,X      DETERMINE ADDR IN BUFFER
       LDA    ,Y+      GET BYTE FROM REAORD AREA
       STA    ,X       STORE IN BUFFER
       INC    DCBRBA+2,U ADVANAE POINTER IN BUFFER
       BNE    DW5B     IF IN SAME SECTOR
       LBSR   DSKWRT   REWRITE,SEATOR
       BNE    DW5AA    IF I/O ERROR
       LDD    DCBRBA,U
       ADDD   #1       POINT TO NEXT,SECTOR
       STD    DCBRBA,U
       LBSR   CALSEC   RECALCULATE TRACK &,SECTOR
       BEQ    DW5A      IF OK
DW5AA LEAS    7,S      SCRAP,STUFF IN,STACK
       STA    ,S
       PULS   A,X,Y,PC
DW5A   LBSR   DSKRED
       BNE    DW5AA    IF I/0 ERROR
       LDA    #1
       STA    DCBMDT,U MARK NEW REC AS MODIFIED
DW5B   LDD    ,S       GET COUNT DOWN VALUE
       BEQ    DW5C     IF VARIABLE LENGTH,STRING
        SUBD   #1
        STD    ,S
        BNE    DW5      GO GET ANOTHER CHR
        BRA    DW6
DW5C    LDA    DCBTRM,U STRING DELIMITER
        CMPA   -1,Y     WAS LAST CHR STORED A DELIMITER?
        BNE    DW5      IF NO, KEEP GOING
*
* RECORD HAS BEEN WRITTEN - CLEAN UP
DW6    LDA    #1
       STA    DCBMDT,U ENSURE THIS SECTOR GETS REWRITTEN (EVENTUALLY)
       JMP    RDWRX    CLEAN UP SAME AS FOR READ
*
*************************************************
* RELEASE THE I/O BUFFER
* (USED WHEN USER WANTS TO CONTROL,SHARED BUFFER)
* GIVEN: U->DCB
*************************************************
DRELSE LBSR   REWRTE   REWRITE BUFFER CONTEN,S IF NEC,SSARY
       LDD    #$FFFF
       STD    DCBPRN,U FORCE READ NEXT TIME
       CLRA
       RTS
       OPT    L
       TTL    DOS - SUPPORTING SUBROUTINES
       OPT    NOL
**********************************
* POINT "X' AT FAT TABLE IN MEMORY
* GIVEN: U-> DCB CONTAINING DCBDRV
* RETURNED:X
**********************************
ADRFAT LDX    #FATS    FAT TABLE,STORE AREA
       LDA    DCBDRV,U DRIVE CONTAINING FILE
       LDB    #69      NUMBER OF BYTPSHSAVED
       MUL
       LEAX   D,X      POINT TO CORRECT AREA
       RTS
*
*********************************************************
* X F E R   B Y T E S   R O U T I N E S
*********************************************************
* XFER 32 BYTES FROM DCB (AT ,U TO DIRECTORY (AT ,X)
DCBDIR PSHS   D,X,U
        LDB    #32     BYTES TO XFER
        BSR    XFRUX
        PULS   D,X,U,PC
* XFER 32 BYTES FROM DIRECTORY AT ,X TO DCB AT ,U
DIRDCB PSHS   D,X,U
        LDB    #32
        BSR    XFRXU
        PULS   D,X,U,PC
* TRANSFER B BYTES FROM ,U TO ,X
XFRUX   LDA    ,U+
        STA    ,X+
        DECB
        BNE    XFRUX
        RTS
* TRANSFER B BYTES FROM ,X TO ,U
XFRXU   EXG   X,U
        BSR   XFRUX
        EXG   X,U
        RTS
*
*************************************************
* AHEAK DIRECTORY ON THIS DRIVE
* GIVEN: A=ZERO IF LOOKING FOR A MATCH
* A NOT ZERO IF LOOKING FOR AVAILABLE SLOT
* U -> DCB
* RETURNED: A=ZERO IF REQUEST SUCCESSFUL
*           A=FF IF NO MATCH FOUND
*           A=l-8 IF I/O ERROR
*           IF SUCCESSFUL,X-> DIRECTORY ENTRY IN BUFFER
*************************************************
CHKDIR PSHS   D,       SAVE OPTION
       LDD    #$1103
       STA    DCBTRK,U SET TO READ DIRECTORY TRACK
       STB    DCBSEC,U SET TO READ FI,ST DIRECTORY ENTRI,S
* RETRY ONLY IF DRIVE IS READY!
CD1    LDA    >RETRYS
       PSHS   A
       LDA    #2       ** CHANGED IN VER 6 **
       STA    >RETRYS
       LBSR   SYSRED   DO PHYSICAL READ
       PULS   B        GET ORIG NBR OF RETRYS
       BEQ    CD2      IF I/O OK
       STB    >RETRYS
       CMPA   #ERR1    DRIVE NOT READY?
       BNE    CD1A     IF I SHOULD TRY,SOME MORE
CD1E   STA    ,S
       PULS   D,PC
CD1A   LBSR   SYSRED   GO TRY SOME MORE
       BNE    CD1E     IF,STILL ERROR
       BRA    CD2A
* CHECK THE DIRECTORY ENTRIES IN THIS RECORD
CD2    STB >RETRYS
CD2A   LDA #8          NUMBER OF DIRECTORY ENTRYS PER REC
       STA    1,S
       LDX    #SYSBUF POINT AT SYSTEM BUFFER
CD3    TST    ,S       OPTION?
       BEQ    CD5      IF LOOKING FOR A MATCH
       LDA    ,X       LOOK AT 1ST BYTE
       BEQ    CD4      IF I FOUND RE-USABLE,SPACE
       BPL    CD7      IF NOT USEABLE
CD4    CLR    ,S
       PULS   D,PC     RETURN,SUCCESSFULLY
* COMPARE LOOP
CD5    LDA    ,X      LOOK AT 1ST BYTE OF DIRECTORY ENTRY
       BEQ    CD7     IF DELETED ENTRY
       BMI    CD8     IF END OF DIRECTORY ENTRIES
       CLRB           CHARACTER POSITION COUNTER
CD6    LDA    B,X     CHR IN DIRECTORY FILE NAME
       CMPA   B,U     CHR IN DCB FILE NAME
       BNE    CD7     IF NOT A MATCH
       INCB
       CMPB   #11     MORE CHARACTERS TO COMPARE?
       BCS    CD6     IF YES
* MATCH FOUND
       BRA    CD4
*
CD7    LEAX   32,X     POINT TO NEXT DIRECTORY ENTRY
       DEC    1,S      MORE ENTRIES TO LOOK AT IN THIS REC?
       BNE    CD3      IF YES
       INC    DCBSEC,U
       LDA    DCBSEC,U
       CMPA   #12      MORE DIRECTORY RECORDS TO READ?
       BCS    CD1      IF YES
* DIRECTORY ENTRY NOT FOUND ON THIS DRIVE
CD8    LDA    #$FF
       STA    ,S
       PULS   D,PC
*
******************************************
* PHYSICAL DISK READ
* GIVEN: U->DCB
* FUNCTION: READ INTO DCBBUF
*           (NOTE:DSKCON RETRYS ON ERROR 5 TIMES)
* RETURNED:DCBOK = RESULT CODE (ALSO IN A)
******************************************
DSKRED LDA    #2       READ SECTOR OP CODE
       FCB    $8C      SKIP OVER NEXT INSTR
*
***************************
* PHYSICAL DISK WRITE
* ESSENTIALLY SAME AS ABOVE
***************************
DSKWRT LDA    #3       WRITE OP CODE
DSKIO STA     DCBOPC,U
       CLR    DCBMDT,U
* FALL THRU
*
************************************
* CALL DSKCON
* GIVEN:PARAMETERS IN DCB
* FUNCTION: XFER PARAMS TO [C006]
*           CALL DSKCON
*           MOVE RESULT CODE TO DCB
*           LEAVE RESULT CODE IN A
************************************
XFRIOP PSHS   B,X
       LDX    >$C006
       LDD    DCBOPC,U
       STD    ,X++
       LDD    DCBTRK,U
       STD    ,X++
       LDD    DCBBUF,U
       STD    ,X++
XIOENT PSHS   DP
       CLRA
       TFR    A,DP
       BSR    DOIO     DO I/O
       PULS   DP
       CLRA
       LDB    ,X       GET RESULT CODE
       BEQ    XIOX     IF NO ERROR, EXIT
* GENERATE ERROR NUMBER BASED ON WHICH BIT IS ON
XIOA   LSLB              IS THIS BIT SET?
       BCS    XIOB     IF YES
       INCA
       BRA    XIOA
XIOB   INCA
XIOX   PULS   B,X,PC
ZZ     EQU    ERR1+ERR2+ERR3+ERR4+ERR5+ERR6+ERR7+ERR8
* THE ABOVE LINE SIMPLY PUTS ERR1-8 ON THE XREF MAP
DOIO   PSHS   D,X,Y,U
       LDA    >RETRYS
       LDX    >$C004
       JMP    4,X
*
********************************************
* PHYSICAL DISK READ - SYSTEM FUNCTIONS
* SAME AS DSKRED EXCEPT SYSTEM'S BUFFER USED
********************************************
SYSRED LDA    #2
SYSIO PSHS    B,X
       LDB    DCBDRV,U
       LDX    >$C006
       STD    ,X++
       LDD    DCBTRK,U
       STD    ,X++     TRACK & SECTOR
       LDD    #SYSBUF
       STD    ,X++
       BRA    XIOENT   FINISH UP LIKE USER IO
*
****************************************
* PHYSICAL DISK WRITE - SYSTEM FUNCTIONS
****************************************
SYSWRT LDA    #3
       BRA    SYSIO
*
**************************************************************************
* IF DATA IN BUFFER HAS BEEN MODIFIED (OCBMDT NOT = 0l CHECK
* TO SEE IF WRITES ARE ALLOWED. IF NO, DO NOT SET ERROR - JUST EXIT.
* IF YES, REWRITE BLOCK IN BUFFER (EXIT WITH ERROR IN A IF WRITE NO GOOD.)
*
* GIVEN: U->DCB CONTAINING DCBPRN = PHYSICAL REC NUMBER THAT IS IN BUFFER.
**************************************************************************
REWRTE TST    DCBMDT,U DATA IN BUFFER MODIFIED?
       BNE    RW1      IF YES
RWX    CLRA
RWXX   RTS
RW1    LDA    DCBCFS,U
       ANDA   #OUT     ARE WRITES ALLOWED?
       BEQ    RWX      IF NO, EXIT WITH NO ERROR
       BSR    CSENT    RE-ESTABLISH TRK & SEC FROM PRN
       BNE    RWXX     IF NG, EXIT WITH ERROR
       BRA    DSKWRT   GO DO REWRITE & RETURN TO CALLER
*
************************************************************
* CALCULATE RELATIVE BYTE ADDRESS FROM LOGICAL RECORD NUMBER
* (DCBRBA = DCBRSZ * DCBLRN)
************************************************************
CALRBA PSHS   X,Y,U
        LEAX   DCBRBA,U
        LEAY   DCBRSZ,U
        LEAU   DCBLRN,U
        CLR    ,X
        CLR    1,X
        CLR    2,X
        LDA    1,Y
        LDB    1,U
        MUL
        STD    1,X
        LDA    1,Y
        LDB    ,U
        MUL
        ADDD   ,X
        BCS    CRBAER IF CARRY
        STD    ,X
        LDA    ,Y
        LDB    1,U
        MUL
        ADDD   ,X
        BCS    CRBAER
        STD    ,X
        LDA    ,y
        LDB    ,U
        MUL
        ADDB   ,X
        BCS    CRBAER
        STB    ,X
        TSTA
        BNE    CRBAER
        PULS   X,Y,U,PC
CRBAER  LDA    #ERR16
        PULS   X,Y,U,PC
*
************************************************************
* CALCULATE TRACK & SECTOR
*
* GIVEN: DCBPRN = RELATIVE RECORD NUMBER
* FUNCTION: FOLLOW CLUSTER CHAIN UNTIL PROPER CLUSTER FOUND
* RESULT: DCBTRK & DCBSEC IF RECORD IN RANGE
* THEY POINT TO LAST SECTOR IF NOT IN RANGE.
* A = ZERO IF SUCCESSFUL
*      NON ZERO IF NOT
************************************************************
CALSEC LDD   DCBRBA,U DESIRED REC NUMBER
       STD   DCBPRN,U SAVE AS THE REC IN THE BUFFER
CSENT LDA    DCBFCL,U
       PSHS A,X
       LDX   #FATS
       LDA   DCBDRV,U
       LDB   #FATSZ
       MUL
       LEAX D,X       POINT TO PROPER FAT TABLE
       LDD   DCBPRN,U REC NUMBER DESIRED
       TST   ,S
       BMI   CS3      IF AT END OF CLUSTERS (NULL FILE>
CS1    SUBD #9
       BCS   CS4      IF IN THIS CLUSTER
      PSHS   D
      LDA    2,S
      LDA    A,X      GET NEXT CLUSTER POINTER
      BMI    CS2      IF AT END OF CLUSTERS
      STA    2,S
      PULS   D
      BRA    CS1
CS2    PULS   D
*
* REC IS BEYOND END OF CURRENT CLUSTERS
* AM I ALLOWED TO ADD ANOTHER CLUSTER?
CS3    LDA    DCBCFS,U
       ANDA   #EXTEND AM I ALLOWED?
       BNE    CS6      IF YES, GO TRY IT
CS3A   LDA    #ERR17   EXTENSION NOT ALLOWED
       BRA CSERR
*
* RECORD IS IN THIS CLUSTER
CS4    ADDB   #10      (RESULT IS 1-9)
* IS THE SECTOR NUMBER IN B IN USE IN THIS CLUSTER YET?
       LDA    ,S (CLUSTER NUMBER)
       TST    A,X      IS THIS CLUSTER THE LAST IN THE FILE?
       BPL    CS5      IF NO
       PSHS   D        CLUSTER NUMBER/SECTOR NUMBER
* IS THIS RECORD BEYOND CURRENT LAST SECTOR USED?
       LDB    A,X
       ANDB   #63      CURRENT LAST SECTOR USED
       CMPB   1,S      THIS ONE
       BCC    CS4A     IF THIS IS LESS OR EQUAL TO CURRENT END
       LDB    DCBCFS,U GET FILE STATUS
       ANDB   #EXTEND FILE EXTENSIONS ALLOWED?
       BNE    CS4B     IF YES
CS4AE PULS    D
       BRA    CS3A     EXTENSION NOT ALLOWED
CS4A   BNE    CS4C     IF NOT IN LAST SECTOR
       LDA    DCBCFS,U
       ANDA   #EXTEND ALLOWED?
       BNE    CS4C     IF ITS OK
* IS REC BEYOND LAST BYTE?
       LDB    DCBRBA+2,U
       CLRA
       CMPD   DCBNLS,U
       BCS    CS4C     IF OK
       BRA    CS4AE    IF NG
* EXTEND LAST SECTOR IN THIS CLUSTER
CS4B   LDB    1,S      SECTOR NUMBER
       ORB    #$C0
       STB    A,X      PUT IN FAT TABLE
* FAT HAS CHANGED - CAN I BYPASS UPDATE THIS TIME?
       LDA    DCBCFS,U
       ANDA   #FAST
       BNE    CS4C     IF YES
       BSR    WRTFAT   RE-WRITE FAT TABLE TO REFLECT CHANGE
       BEQ    CS4C     IF I/O WAS OK
       PULS   D
       LDA    #ERRl8   FAT RW ERR
CSERR STA     ,S
       PULS   A,X,PC
CS4C   PULS   D        CONTINUE - IT IS NOW WITHIN RANGE OF FILE
* RECORD IS IN RANGE OF FILE - XLATE CLUSTER INTO TRACK & SECTOR
CS5    LDA    ,S       CLUSTER NUMBER
       LSRA            IS THIS AN ODD CLUSTER?
       BCC    CS5A     IF NO
       ADDB   #9       IF YES, USE SECTORS 10-l8
CS5A   STB    DCBSEC,U
       CMPA   #17      IS CLUSTER BELOW DIRECTORY?
       BCS    CS5B     IF YES
       INCA            IF NOT GO ONE TRACK FARTHER
CS5B   STA    DCBTRK,U
       CLR    ,S
       PULS   A,X,PC
*
* TRY TO ADD ANOTHER CLUSTER TO THE FILE
* NEXT CLUSTER USED WILL BE THE CLOSEST ONE TO THE LAST ONE USED BY
* THIS FILE. IF FIRST EVER FOR THIS FILE, IT WILL BE CLOSEST TO MIDDLE.
CS6    LDB    ,S       LAST CLUSTER NUMBER USED
       BPL    CS6A     IF NOT VERY FIRST ASSIGNED TO FILE
       LDB    #34      START SEARCH AT CLUSTER 34
CS6A   CLRA            STARTING DISPLACEMENT
       PSHS D
* LOOP TO LOOK FOR AN AVAILABLE CLUSTER
CS7    LDA    1,S      LAST CLUSTER OF FILE
       ADDA   ,S       ADD DISPLACEMENT
       CMPA   #68      IN RANGE OF TABLE?
       BCC    CS7A     IF NO
       LDB    A,X      GET FAT TABLE BYTE
       CMPB   #$FF     IS IT AVAILABLE
       BEQ    CS8      IF YES
CS7A   LDA    1,S
       SUBA   ,S       LOOK THE OTHER WAY
       BCS    CS7B     IF NOT IN RANGE OF THE TABLE
       LDB    A,X      GET FAT TABLE BYTE
       CMPB   #$FF     AVAILABLE?
       BEQ    CS8      IF YES
CS7B   LDA    ,S
       INCA
       STA    ,S
       CMPA   #68      HAVE I TRIED ALL POSSIBILITIES?
       BCS    CS7      IF NOT YET
       PULS   D        NORMALIZE STACK
       LDA    #ERR22   DISK FULL
       BRA    CSERR
CS8    LDB    2,S      ORIGINAL ENDING CLUSTER
       BPL    CS8A
       STA    DCBFCL,U THIS IS FIRST CLUSTER
       BRA    CS8B
CS8A   STA    B,X      ADD TO CHAIN
CS8B   LDB    #$C0     SAY NONE OF THESE SECTORS USED
       STB    A,X
       PULS   D
       PULS   A,X      NORMALIZE STACK
       JMP    CSENT    GO TRY AGAIN FROM THE TOP!
*
************************************************
* REWRITE FAT TABLE ON DIRECTORY TRACK
*
* GIVEN: X-> CORRECT FAT TABLE IN MEMORY
*        U-> DCB CDNTAINING CDRRECT DRIVE NUMBER
************************************************
WRTFAT PSHS    X
       LDX     >$C006
       LDA     #3       WRITE
       STA     ,X+
       LDA     DCBDRV,U
       STA     ,X+
       LDD     #$1102   TRACK 17, SECTDR 2
       STD     ,X++
       LDD     ,S       ADDR DF FAT TABLE
       STD     ,X++
       PSHS    DP
                CLRA
       TFR     A,DP
       JSR     [$C004] DD ID
       PULS    DP
       LDA     ,X
       PULS    X,PC
       TTL     RESULT   DDS - PAGING & DVERLAYS
*
**************************************************************************
* ON DISK, THIS PROGRAM BEGINS HERE, EVERY THING THAT PRECEEDS THIS POINT
* IS RECORDED ON DISK AFTER THE END OF THE OVERLAYS. WHEN DOS IS FIRST
* LOADED INTO MEMORY, THE ROUTINE CALLED "OVRLAY" SHIFTS THOSE ROUTINES
* DOWN TO THEIR PROPER PLACE.
**************************************************************************
DOS    JMP    DOS1     JUMP DVER DISPLACEMENTS TD DVERLAYS
       FDB    B1-DOS
       FDB    B2-DOS
       FDB    B3-DOS
       FDB    B4-DOS
       FDB    B5-DOS
       FDB    B6-DOS
       FDB    B7-DOS
       FDB    B8-DOS
       FDB    B9-DOS
       FDB    B10-DOS
       FDB    B11-DOS
       FDB    B12-DOS
       FDB    B13-DOS
       FDB    B14-DOS
       FDB    B15-DOS
       FDB    B16-DOS
       FDB    B17-DOS
       FDB    B18-DOS
       FDB    B19-DOS
       FDB    B20-DOS
* MINIMUM INITIALIZATION FOLLOWS
DOS1   DOS    DO,INIT GO INITIALIZE (MENU ETC)
       TSTA
       BEQ    DOS2
       JSR    [ERROR]
DOS2   JMP    OBASIC
DOS3   LDD    #OVRLAY
       STD    >OLYLOC
       RTS
*
******************************************************
* 8 BIT PRINTER DRIVER
* GIVEN: A=CHR TO BE SENT TO PRINTER
* RETURNED:A IN TACT
*          CC = Z CONDITION IF SENT OK
*          CC = NON-Z IF PRINTER NOT READY - TRY AGAIN
******************************************************
* IS PRINTER READY?
DPRNT PSHS    D,X
       LDA    >U4BDR
       LSRA   
       BCC    DP1     IF READY
       LDA    #1      SET NON-Z CONDITION
       PULS   D,X,PC
DP1    PSHS   CC      SAVE INTERUPT STATUS
       DSABLI         NO INTERUPTS DURING HARD LOOP TIMING
       LDA    1,S     CHR TO SEND
       CLRB   
       BSR    LPSND   SEND START BIT
       LDB    #8      BITS TO SEND
       PSHS   B       LOOP COUNTER
DP2    CLRB   
       LSRA
       ROLB
       ROLB   
       BSR    LPSND   SEND THE BIT
       DEC    ,S
       BNE    DP2     GO BACK
       PULS   B
*INITIATE STOP BIT (IT CONTINUES UNTIL PRINTER SAYS 'READY">
       LDB   #2
       STB   >U4ADR
       PULS CC        RESTORE INTERUPT STATUS
       CLRA           SET ZERO CONDITION CODES
       PULS D,X,PC
LPSND STB    >U4ADR   LATCH BIT TO OUTPUT
       LDX   >RATE    TIME CONSTANT FOR TRANSMISSION
LPDLP LEAX -1,X
       BNE   LPDLP
       RTS
*
************************************************
* TURN ON OR OFF A TIME DRIVEN ROUTINE
* GIVEN: U-> START OF ROUTINE THAT FOLLOWS SPECS
************************************************
DTMEON PSHS   D,U
       TSTA             REQ FOR ON OR OFF?
       BEQ    DTMEOF    IF OFF
       LDD    >IRQ+1
       STD    1,U
       LEAU   3,U
       STU    >IRQ+1
       PULS   D,U,PC
*
*********************************
* TURN OFF A TIME DRIVEN ROUTINE
* GIVEN: U -> START OF ROUTINE
*********************************
DTMEOF LEAU   3,U       ADDR STORED IN CHAIN
       PSHS   X,U
       LDU    #IRQ+1
DTO    LDX    ,U        LOOK AT ADDR OF NEXT R,UTINE
       CMPX   #STDTME   IS IT END OF CHAIN?
       BEQ   DTO2      IF YES, GET OUT
       CMPX   2,S       IS IT THE ONE SOUGHT?
       BEQ   DTO3      IF YES
       TFR    D,U
       LEAU   -2,U
       BRA    DTO
DTO2   PULS   X,U
       PULS   D,U,PC
* X POINTING AT DESIRED ROUTINE
* U POINTING AT WHERE THAT POINTER CAME FROM
DTO3   LDX    -2,X     GET ADDR THAT DESIRED R,UTINE POINTS TO
       STX    ,U       UNLINK HIS ROUTINE
       PULS   X,U
       PULS   D,U,PC
*
***************************************************************
* STANDARD TIME ROUTINE - LINKED IN BY INITIAL START UP ROUTINE
***************************************************************
STMX   JMP    >0
STDTME LDD    >CLOCK
       INCD
       STD    >CLOCK
       CLRA
       TFR    A,DP     ENSURE ROM ROUTINE USES PAGE ZERO
       BRA    STMX
*
***********************************************************
* CALL A SYSTEM OVERLAY (OR USER OVERLAY)
* GIVEN: OVERLAY NUMBER IN 'A"
* OVERLAY IS LOADED IF NOT PRESENT IN MEMORY
* NOTE: X IS NOT PRESERVED - USED FOR OVERLAY BASE ADDRESS
***********************************************************
USROLY ORA    #$80
SYSOLY LDX    >OLYLOC POINT AT CURRENT OVERLAY LOAD AREA
       CMPA   -1,X     IS THE DESIRED OVERLAY ALREADY THERE?
       BEQ    SYSO3    IF YES
       PSHS   B
       TSTA            SYSTEM OR USER?
       BMI    SYSO1    IF USER
       BSR    SYSLOD   LOAD THE OVERLAY
       BRA    SYSO2
SYSO1 BSR     USRLOD   LOAD THE OVERLAY
       BEQ    SYSO2    IF OK
       PULS   B,PC     IF LOAD ERROR
SYSO2 PULS    B
SYSO3 LDX     #SYSO4   WHERE TO GO ON THE WAY BACK FROM THE OVERLAY
       PSHS   X
       LDX    >OLYLOC OVERLAY LOAD AREA
       LEAX   2,X      ENTRY POINT WITHIN OVERLAY
       PSHS   X
       LEAX   -2,X     PROVIDE USER WITH HIS BASE ADDRESS
       PSHS   B,X
       LDD    ,X       GET SIZE OF OVERLAY
       LEAX   D,X      POINT TO END OF OVERLAY
       LEAX   3,X      POINT TO BASE OF NEXT OVERLAY AREA
       STX    >OLYLOC
       PULS   B,X,PC   BASE ADDR OF OVERLAY
*
* ON THE WAY BACK, ADJUST OLYLOC
SYSO4 PSHS    CC,D,X
       LDX    >OLYLOC
       LEAX   -3,X
       LDD    ,X       GET SIZE OF THIS OVERLAY
       NEGD
       LEAX   D,X      POINT AT BEGINNING OF OVERLAY I AM EXITING
       STX    >OLYLOC SAVE IT
       PULS   CC,D,X,PC
*
************************************************************
* RETURN FROM ONE OVERLAY & XFER CONTROL TO ANOTHER
* GIVEN: STACK NORMALIZED AS IF READY TO RTS FROM AN OVERLAY
*        A = DESIRED OVERLAY NUMBER
************************************************************
DUSRGO ORA    #$80
DGO    PSHS   D        SAVE D
       LDD    4,S      (RET ADDR TO SYS04)
       STD    2,S
       LDD    #SYSOLY CAUSE "RETURN" TO SYSOLY AFTER "UNDOING"
       STD    4,S
       PULS   D,PC     RETURNS TO SYS04
*
*****************************************
* LOAD A SYSTEM OVERLAY (OR USER OVERLAY)
* GIVEN: A = OVERLAY NUMBER
*****************************************
USRLOD ORA    #$80
       PSHS   Y,U
       LDY    >USRBSE
       LDU    #USRDCB
       BSR    PAGEIN   LOAD THE OVERLAY
       BEQ    SLDX     IF LOADED OK
       LDA    #ERR23
SLDX   PULS   Y,U,PC
SYSLOD PSHS   Y,U
       LDY    #DOS+1   LOC OF OVERLAY'S RBA TABLE IN MEMORY
       LDU    #DOSDCB POINT AT SYSTEM'S DCB
       BSR    PAGEIN   LOAD THE OVERLAY
       BNE    ABORT    IF SYSTEM FAILURE
       PULS   Y,U,PC
*
*********************************************
* FATAL ERROR OCCURRED IN DOS - CAN'T PROCEED
*********************************************
ABORT LDX     #$400    VID
       LDU    #ABTMSG
       LDB    #16
       LBSR   XFRUX
       LDU    #$400
       LDB    #256-16
       LBSR   XFRUX
       BSR     DERR     WAIT FOR A KEYSTROKE
OBASIC TSTA
       BEQ     OBAS1
       LDS     #STACK
       JSR     DOS3     RESET STACK & OLYLOC
       DOS     DO,MENU
OBAS1 CLR      >$71
       JMP     [$FFFE]
ABTMSG FCC     /SYSTEM/
       FCB     $60
       FCC     /FAILURE/
       FDB     $6060
*
**************************
* USER ABORT ROUTINE
* GIVEN: ERROR NUMBER IN A
**************************
DERROR TFR     A,B
       LDA     #1       (ADD 256 TO IT0
       PSHS    D        SAVE FOR LATER
       LDD     #50      START OF INSTRUCTIONS
       LDY     #69      END OF INSTRUCTIONS
       LDU     #0       CLEAR SCREEN FIRST
       BSR     DOMAP    GIVE INSTRUCTIONS
       PULS    D
       TFR     D,Y
       BSR     DOMAP    DISPLAY ERROR
DERR   SYSTEM POLCAT    WAIT FOR ANY KEYSTROKE
     BEQ     DERR
     RTS
*
*************************
* DO MAP DISPLAY FUNCTION
*************************
DOMAP PSHS     D,Y,U
       DOS     DO,MAP
       PULS    D,Y,U,PC
*
************************************************************************
* L O A D    O V E R L A Y    R O U T I N E
*
* GIVEN: A=OVERLAY NUMBER
*        U-> PROGRAM DCB
*        Y-> TABLE CONTAINING RBA'S OF OVERLAYS
*        THE FILE MUST HAVE PREVIOUSLY BEEN OPENED!
************************************************************************
PAGEIN LDX     >OLYLOC
       STA     -1,X
       TFR     A,B
       ANDB    #$7F
       LSLB             2 BYTES PER VECTOR
       CLRA
       LDD     D,Y      GET RBA OF START OF OVERLAY
       ADDD    #5       ADJUST TO RBA WITHIN DISK FILE
       CLR     DCBRBA,U
       STD     DCBRBA+1,U
       LDD     #2       LENGTH OF A SIZE FIELD
       STD     DCBRSZ,U SET TO READ 2 BYTES
       STX    DCBLRB,U
       LDD    #$FFFF
       STD    DCBPRN,U FORCE INITIAL PHYSICAL READ
       BSR    PIRD
       LEAX   2,X
       LDD    [DCBLRB,U] LENGTH OF ROUTINE (INCLUDING SIZE WORD)
       STX    DCBLRB,U WHERE REST OF OVERLAY GOES
       LEAX   D,X      POINT TO END OF OVERLAY + 2
       STD    -2,X     SAVE HIS SIZE AT END
       CLR    ,X       SAY NO VALID OVERLAYS FOLLOW
       SUBD   #2       SIZE OF THE REST
       STD    DCBRSZ,U SAVE AS RECORD SIZE
       BSR    PIRD
       CLRA
       RTS
PIRD   DOS    READ,RBA
       BEQ    PIERX
       LEAS   2,S      BYPASS RET ADDR
PIERR LDX     >OLYLOC
       CLR    ,X       SAY THIS OVERLAY DOSN'T EXIST IN MEMORY
       TSTA            SET COND CODES
PIERX RTS
*
******************************************************
* MINIMUM LOGIC TO LOAD & PASS CONTROL TO USER PROGRAM
* JUMP HERE FROM OVERLAY 12
******************************************************
B12A   DOS    READ,RBA READ IN THE ROOT SEGMENT
       LDX    DCBLRB,U BASE OF PROGRAM
       TFR    X,PC     JUMP TO ROOT
*
       FCB    0        PLACE WHERE NUMBER OF 1ST OVERLAY LOADED GOES

*
*** **********************************************************************
*           O V E R L A Y   S E C T I O N   F O L L O W S
* ALL SECTIONS THAT FOLLOW ARE RELOCATABLE.
* (THE FIRST OVERLAY IS LOADED AT THIS ADDRESS)
**************************************************************************
*
* THE FOLLOWING ROUTINE SIMPLY SHIFTS PART OF DOS DOWN TO $989. IT
* IS LOADED AFTER THE END OF THE REST OF THE PGM SO AS TO PREVENT
* CONFLICTS WITH BASIC.
* IT IS CLOBBERED WHEN FIRST OVERLAY IS LOADED!
OVRLAY LDX    #LASTPG
       LDU    #$989
       LDY    #DOS-ORGIN AMOUNT OF PGM TO XFER
OVLP   LDA    ,X+
       STA    ,U+
       LEAY   -1,Y
       BNE    OVLP
* INITIALIZE VECTORS AT $600

; KJF - Use this as the entry point when loading from a "non-packaged" executable,
;       since we'll load exactly where needed.
InitWithoutRelocation:

       LDU    #$600
       LDX    #VECINI
       LDB    #ENDVEC-VECINI
       JSR    XFRXU    MOVE IT TO $600
* FROM THIS POINT ON, VECTORS AT $600 MAY BE USED
       LDS    #STACK
       LDX    >IRQ+1   VECTOR TO DISK ROM TIME ROUTINE
       LEAX   5,X      BYPASS CHECK FOR WHICH INTERUPT IT IS
       STX    >IRQ+1   STORE REVISED ENTRY POINT
       LDU    #STMX
       DOS    TIME,ON
       LDD    >POLCAT ADDR OF ROM KBD SCAN ROUTINE
       STD    >KEYIN   SAVE IN KEYIN VECTOR
* DETERMINE MEMORY SIZE
       LDX    #$7FFF   END OF 32K
       LDA    ,X
       COMA
       STA    ,X
       CMPA   ,X
       BEQ    OVLP1    IF 32K MACHINE
       LDX    #$3FFF   FOR 16K
OVLP1 STX     >MAXMEM
       LDA    #4       MAX NUMBER OF DRIVES
       STA    DRIVES
       LDU    #DOSDCB
       LDS    #STACK
       JSR    DOS3
       DOS    OPEN,INPUT READ ONLY
       JMP    DOS
*
VECINI FDB    DOPEN    POINTER TO OPEN FUNCTION
       FDB    DCLOSE
       FDB    DREAD
       FDB    DWRITE
       FDB    DRELSE   RELEASE I/O BUFFER
       FDB    SYSOLY   CALL SYSTEM OVERLAY
       FDB    DGO      JUMP BETWEEN SYSTEM OVERLAYS
       FDB    SYSLOD   LOAD A SYSTEM OVERLAY
       FDB    USROLY   CALL USER OVERLAY
       FDB    DUSRGO   JUMP BETWEEN USER OVERLAYS
       FDB    USRLOD   LOAD A USER OVERLAY
       FDB    DERROR   USER FATAL ERROR EXIT
       FDB    DTMEON   TIME ROUTINE ON/OFF
       FDB    DPRNT    B BIT PRINTER DRIVER
       FDB    0        SLOT FOR KEVIN
       FDB    OBASIC   RETURN TO BASIC
       FDB    0        INITIAL CLOCK VALUE
       FCB    5        INITIAL RETRY COUNT
       FDB    $AE      PRINTER TIME CONSTANT
       FDB    OVRLAY   LOAD ADDRESS FOR NEXT OVERLAY
       FDB    0        BASE ADDR OF USER PGM + 1
       FDB    RETURN   HOOK1
       FDB    RETURN   HOOK2
       FDB    RETURN   HOOK3
       FDB    RETURN   HOOK4
       FDB    RETURN   HOOKS
       FDB    $3939    RETURN CODE FOR HOOKS
* INIT COPY OF DOSDCB
       FCC    /DOS     BIN/
       FCB    0,0,0,0,0,0,0,0,0
       FCB    0,0,0,0,0,0,0,0,0,0,0,0
       FCB    0,$FF,0,0
       FDB    SYSBUF
       FCB    0
       FDB    SYSBUF
       FCB     0,0,0,0,0,0,0,0
* INIT COPY OF MSGDCB
       FCC     /DOS     BAS/
       FCB     0,0,0,0,0,0,0,0,0
       FCB     0,0,0,0,0,0,0,0,0,0,0,0
       FCB     0,$FF,0,0
       FDB     SYSBUF
       FCB     0
       FDB     0        (SET WHEN USED)
       FCB     0,0,0,0,0,0,0,0
* INIT COPY OF USER PGM DCB
       FCC     /        BIN/
       FCB     0,0,0,0,0,0,0,0,0
       FCB     0,0,0,0,0,0,0,0,0,0,0,0
       FCB     0,$FF,0,0
       FDB     SYSBUF
       FCB     0
       FDB     00
       FCB     0,0,0,0,0,0,0,0
*
ENDVEC FCB     0        END OF PRESET DATA

    ; KJF: Skip the overlay section if we're doing a special "DOS Core" build.
    IFNDEF SKIP_OVERLAY_SECTION

*
**************************************************************************
* INITIAL START UP - CHECK FOR AUTO EXECUTE
*
**************************************************************************
B1     FDB    B2-B1    SIZE OF OVERLAY
* CHECK FOR AUTO PROGRAM EXECUTION
       LDD    #$1
       LDY    #$1
       LDU    #$0
       JSR    DOMAP    CLR SCREEN & IF AUTO EXISTS, DISPLAY IT
       LDX    #USRDCB
       LDB    #8           NAME LENGTH
       LDA    ,U           GET 1ST CHR FROM SCREEN
       CMPA   #$60         IS IT A BLANK
       BEQ    MENU0        IF YES, NO AUTO FUNCTION
STRT1 LDA     ,U+
       CMPA   #$60
       BCS    STRT2
       EORA   #$40
STRT2  STA    ,X+
       DECB
       BNE    STRT1
       DOS    GO,EXEC      GO LOAD & EXECUTE PROGRAM
MENU0 DOS     GO,MENU      GO DISPLAY MENU & RE-INITIALIZE
*
*******************************************************
* MAIN MENU SELECTION 2 - EXECUTE A PROGRAM
*******************************************************
B2     FDB    B3-B2    SIZE OF OVERLAY
       LDD    #512     STARTING LINE NUMBER
       LDY    #549     ENDING NUMBER
       LDU    #0
       JSR    DOMAP    DISPLAY SCREEN FORMAT & GET ADDR OF INPUT FIELD
* NOTE UU -> FIRST INPUT FIELD ON SCREEN
       LDX    #USRDCB POINT AT DCB
       PSHS   X,U      ADDR OF VID AREA & DEST AREA
       DOS    DO,FIELDI INPUT A FIELD
       PULS   X,U
       DOS    GO,EXEC GO EXECUTE IT
*
************************************************
* MAIN MENU SELECTION 3 - TURN ON CLOCK DISPLAY
************************************************
B3     FDB    B4-B3    SIZE OF OVERLAY
       LDD    MAXMEM
       SUBD   #B14-B13+5 ALLOW ROOM FOR CLOCK ROUTINE
       STD    MAXMEM
       LDY    OLYLOC
       PSHS   Y
       STD    OLYLOC
       LDU    #$400+32-8 DISPLAY AT TOP RIGHT CORNER
       CLRB
       LDY    #7
       DOS    DO,REALTM TURN ON DISPLAY
       LEAS   4,S      NORMALIZE STACK
       PULS   Y
       STY    OLYLOC
       DOS    GO,MENU
*
************************************************
* MAIN MENU SELECTION 4 - DISPLAY FREE SPACE MAP
************************************************
B4     FDB    B5-B4    SIZE
       LDD    #70      START OF SCREEN FORMAT
       LDY    #99      END OF FORMAT
       LDU    #0
       JSR    DOMAP    DISPLAY FORMAT
       CLRA
       PSHS   A        (DRIVE COUNTER)
       LDU    #$400    VID BUFFER
       BSR    FRES1    FIND STARTING DISPLAY POSN
* LOOP ONCE PER DRIVE
FRE1   CMPU   #$5FF    MORE DISPLAY ROOM?
       BCC    FREX     IF NO
       PSHS   U        SAVE NEXT DISPLAY ADDRESS
       LDX    >$C006   POINT AT PARAMETERS
       LDA    #2       (READ)
       LDB    2,S      (DRIVE)
       STD    ,X++
       LDD    #$1102   (TRK 17, SEC 2)
       STD    ,X++
       LDD    #SYSBUF
       STD    ,X++
       LDA    #2       (ONLY 2 RETRYS)
       STA    >RETRYS
       JSR    DOIO
       LDA    #5       (RESTORE TO 5)
       STA    >RETRYS
       PULS   U        (DISPLAY LOC)
       LDY    #SYSBUF
       LDB    #68      LOOP COUNT
       LDA    ,X       RESULT
       BEQ    FRE5     IF OK
FRE3   LDA    #$58     (X)
       BSR     FRESET
       DECB
       BNE     FRE3
FRE4   INC     ,S      DRIVE COUNT
       LDA     ,S
       CMPA    #4      MORE DRIVES TO GO?
       BCS     FRE1    IF YES
FREX   JSR     DERR    WAIT FOR A KEYSTROKE
       PULS    A
       DOS     GO,MENU
       RTS
       * DISPLAY FOR THIS DRIVE
FRE5   LDA     ,Y+
       BMI     FRE6    IF PART OR ALL AVAILABLE
       LDA     #$58    (X)
       BRA     FRE8
FRE6   CMPA    #$FF    ALL AVAILABLE?
       BNE     FRE7    IF PART USED
       LDA     #$6E    (PERIOD)
       BRA     FRE8
FRE7   ANDA    #$F
       ORA     #$70
FRE8   BSR     FRESET
       DECB
       BNE     FRE5
       BRA     FRE4    GO BACK FOR NEXT DRIVE
       *
       * STORE CHR ON SCREEN & FIND NEXT DISPLAY POSN
FRESET STA    -1,U
FRES1 LDA     ,U+
       CMPA   #$6E     PERIOD?
       BEQ    FRESX
       CMPU   #$600    END OF SCREEN?
       BNE    FRES1    IF NO
       LEAU   -1,U
FRESX  RTS
       *
       ************************************
       * MAIN MENU SELECTION 5 - COPY FILES
       ************************************
B5     FDB    B6-B5    SIZE OF OVERLAY
       PSHS   X
       BRA    B5A
; B5DCB1 RMB    DCBSZ  KJF: Changing to FCBs so that a 0 is output, to match the
; B5DCB2 RMB    DCBSZ       shipping version of DOS.BIN.
B5DCB1 ZMB    DCBSZ
B5DCB2 ZMB    DCBSZ
B5A    LDD    #550     START OF FORMAT
       LDY    #599     END OF FORMAT
       LDU    #0       CLEAR SCREEN FIRST
       JSR    DOMAP    DISPLAY SCREEN
       LDB    #7
       DOS    DO,INPTS
       CMPB   #BREAK
       BEQ    B5X
*
* ENTER PUSHED SET UP DCBS
B5J    LDX    #$400
       LDU    ,S       BASE ADDR
       LEAU   B5DCB1-B5,U POINT AT SOURCE DCB
     BSR    B5K      SET UP SOURCE DCB
     LEAU   DCBSZ,U POINT AT DEST DCB
     BSR    B5K
     BRA    B5L
* SETUP A DCB
B5K    BSR    B5TAB
       LDB    #8
       LEAY   ,U
       BSR    B5MOV
       BSR    B5TAB
       LEAY   DCBFEX,U
       LDB    #3
       BSR    B5MOV    MOVE EXTENTION
       BSR    B5TAB
       LDA    ,X
       SUBA   #$70     (ZERO)
       STA    DCBDRV,U
       RTS
B5TAB LDA     ,X+
       CMPA   #$5B
       BNE    B5TAB
       RTS
B5MOV LDA     ,X+
       CMPA   #$60
       BCS    B5MOV1
       SUBA   #$40
B5MOV1 STA    ,Y+
       DECB
       BNE    B5MOV
       RTS
*
B5L    BSR    B5TAB    TO Y/N
       LDB    ,X
       CMPB   #$59     Y
       BEQ    B5M
       CMPB   #$4E     N
       BNE    B5X
B5M    LDX    ,S       BASE
       LEAU   B5DCB1-B5,X
       LEAY   B5DCB2-B5,X
       DOS    DO,COPY
       TSTA
       BEQ    B5X
       JSR    [ERROR]
*
B5X    PULS   X
       DOS    GO,MENU
       RTS
*
*********************************
* DISPLAY SELECTED DIRECTORY LIST
*********************************
B6     FDB    B7-B6
       LEAX   B6ARG-B6,X
       PSHS   X
       BRA    B6A
B6ARG FCB     0,0
      FCC    /           /
      FCC    /                                /
B6A   LDD    #600
      LDY    #649
      LDU    #0
      JSR    DOMAP    DISPLAY INPUT SCREEN
* GET USER INPUTS
      LDB    #3       NUMBER OF FIELDS
      DOS    DO,INPTS GET INPUTS
* SETUP ARGUMENTS
      LDU    ,S
      LEAU   2,U      POINT TO NAME
      LDX    #$400
      BSR    B6TAB
      LDB    #8
      BSR    B6MOV
      BSR    B6TAB
      LDB    #3
      BSR    B6MOV
      BSR    B6TAB
      LDA    ,X+
      ANDA   #3
      LDU    ,S
      STA    ,U
      CLR    1,U
* PREPARE LISTING
B6D   LDA    ,X+
      CMPA   #$6E
      BEQ    B6E
      CMPA   $6F I
      BEQ    B6E
      CMPX   #$600
      BCS    B6D
B6D1 JSR     DERR     WAIT FOR A KEYSTROKE
      PULS   U
      DOS    GO,MENU
      RTS
B6E   LDU    ,S
      PSHS   X,U
      DOS    DO,SCNDIR
      PULS   X,U
      LDA    1,U      ENTRY FOUND?
      BMI    B6D1     IF NO
      LEAU   13,U     POINT AT NAME FOUND
      LEAX   -1,X
      LDB    #8       MAX NAME LENGTH
  * DISPLAY NAM
B6F   LDA    ,X
      CMPA   #$6E
      BNE    B6G
      LDA    ,U+
      ORA    #$40
      STA    ,X+
      DECB
      BNE    B6F
  * DISPLAY EXTENT
B6G   LDU    ,S
      LEAU   21,U     POINT AT EXT
      LDA    ,X+
    CMPA   #$6F     /
    BNE    B6D      GO GET NEXT ONE
    LDB    #3
B6H  LDA    ,X
    CMPA   #$6E
    BNE    B6D
    LDA    ,U+
    ORA    #$40
    STA    ,X+
    DECB
    BNE    B6H
    BRA    B6D
B6TAB LDA     ,X+
       CMPA   #$5B
       BNE    B6TAB
       RTS
B6MOV LDA     ,X+
       CMPA   #$60
       BCS    B6MOV1
       SUBA   #$40
B6MOV1 STA    ,U+
       DECB
       BNE    B6MOV
       RTS
*
***********************************
* FILL FOR ROUTINES NOT YET WRITTEN
***********************************
* (OTHER MAIN GO,MENUMENU FUNCTIONS)
B7     FDB    B8-B7    SIZE OF OVERLAY
       DOS    GO,MENU
       RTS
*
B8     FDB    B9-B8    SIZE OF OVERLAY
       DOS    GO,MENU
       RTS
*
B9     FDB    B10-B9   SIZE OF OVERLAY
       DOS    GO,MENU
       RTS
*
************************************************************************
* GET SCREEN LINES OUT OF BASIC FILE & DISPLAY
*
* GIVEN IN THE STACK(PUSHED BEFORE CALLING:
* (,S = RET ADDR TO UNDO)
* (2,S = RET ADDR TO CALLER)
* 4,S STARTING LINE NUMBER DESIRED
* 6,S ENDING LINE LINE NUMBER DESIRED
* A,S INITIAL DISPLAY LOC
************************************************************************
B10    FDB    B11-B10 OVERLAY SIZE
MAPBSE EQU    B10      (ONLY THIS LINE & ONE ABOVE MUST CHG TO USE DIF OVRLAY NBR)
       BRA   MAP1      BYPASS LOCALS
MAPOSW FCB   0         FILE OPEN SW - 0 WHEN OVERLAY LST LOADED. 1 FROM THEN ON
MAPLN   FDB   0         LAST LINE NUMBER READ
*
MAP1    LDU   #MSGDCB   POINT AT DCB
       LDY    >OLYLOC (POINTS BEYOND THIS OVERLAY (WHERE NEXT OVERLAY WOULD GO)
       STY    DCBLRB,U USE AS LOGICAL RECORD BUFFER
       TST    MAPOSW-MAPBSE,X FILE OPENED?
       BNE    MAP3     IF YES
* IF FIRST TIME CALLED, OPEN DISK FILE
       DOS    OPEN,INPUT OPEN DISK FILE
       LDA    #1
       STA    MAPOSW-MAPBSE,X SAY FILE IS OPEN
* RESET TO BEGINNING OF FILE
MAP2   CLRD
       STD    MAPLN-MAPBSE,X RESET LAST LINE READ
       STD    DCBRBA,U
       LDA    #3 (START READING AT RBA 00 00 03)
       STA    DCBRBA+2,U
* CHECK TO SEE IF FILE NEEDS TO BE RESET
* (REQUEST MUST BE > LAST LINE READ)
MAP3   LDD    #$FFFF
       STD    DCBPRN,U TO FORCE RE-READ INTO BUFFER
       LDD    MAPLN-MAPBSE,X LAST LINE READ
       CMPD   4,S      1ST LINE TO BE DISPLAYED
       BCC    MAP2     GO START OVER AT BOF
* CHECK DISPLAY LOC OPTION
       LDD    8,S      STARTING DISPLAY LOC
       BNE    MAP5     IF ADDRESS GIVEN
* CLEAR THE SCREEN
       LDU    #$400
       STU    8,S      START DISPLAY AT TOP OF SCREEN
       LDD    #$6060   BLANKS
       LDY    #256
MAP4   STD    ,U++
       LEAY   -1,Y
       BNE    MAP4
*
* READ/DISPLAY LOOP
* READ A LINE
MAP5   LDU    #MSGDCB POINT AT DCB
       LDD    #4       LENGTH OF LINE NBR & MEM ADDR
       STD    DCBRSZ,U SET TO READ 4 BYTE RECORD
       DOS    READ,RBA
       BNE    MAPERR   IF I/O ERROR
       LDY    >OLYLOC (LOGICAL REC BUFFER)
       LDD    ,Y       GET "MEMORY ADDRESS"
       BEQ    MAP10    IF AT EOF
       LDD    2,Y      GET LINE NUMBER
       STD    MAPLN-MAPBSE,X SAVE FOR FUTURE REFERENCE
       PSHS   D
       CLR    DCBRSZ+1,U SET FOR VARIABLE LENGTH RECORDS
       DOS    READ,RBA READ A STRING
       PULS   D
       BNE    MAPERR   IF I/O ERROR
       CMPD   4,S      IS AT LEAST AS FAR AS STARTING LINE NUMBER?
       BCS    MAP5     NOT FAR ENOUGH, GO READ ANOTHER
       CMPD   6,S      IS IT BEYOND LAST ONE?
       BEQ    MAP6     IF THIS IS THE LAST ONE
       BCC    MAP10    IF AT END OF RANGE
* LINE FOUND - XFER IT TO SCREEN
MAP6   PSHS   X,Y
       LDX    >OLYLOC
       LEAX   1,X      (SKIP THE "REM" CODE)
       LDY    8+4,S    DESTINATION ADDRESS
* MOVE CHARACTER LOOP
MAP7   LDA    ,X+      GET A CHARACTER
       CMPA   DCBTRM,U IS IT THE TERMINATOR BYTE?
       BEQ    MAP9     IF YES
       CMPA   #$40     IS IT SPL CHR?
       BCC    MAP8     IF NO
       ORA    #$40
MAP8   STA    ,Y+
       BRA    MAP7
MAP9   LDX    8+4,S
       LEAX   32,X
       STX    8+4,S
       PULS   X,Y
       BRA    MAP5     GO GET NEXT LINE
* FIND START OF INPUT FIELD
MAP10 LDU     #$400
       LDY    #512     MAX CHRS TO TEST
       LDA    #$5B     (LEFT BRACKET ON SCREEN)
MAP11 CMPA    ,U+
       BEQ    MAP12
       LEAY   -1,Y
       BNE    MAP11
       LDU    #$400    IF NO FIELD FOUND
MAP12 STU     8,S
       CLRA
       RTS
MAPERR LDA    #ERR25
       RTS
*
*********************************************************
* INPUT A FIELD FROM THE KEYBOARD (ECHO ON THE SCREEN)
*
* GIVEN: (,S = RET TO UNDO)
*        (2,S = RET TO CALLER
*        4,S = ADDR OF INPUT FIELD IN WS
*        6,S = ADDR OF INPUT FIELD ON SCREEN
*********************************************************
B11    FDB    B12-B10 SIZE OF OVERLAY
       LDU    6,S
       LDY    4,S
       CMPU   #$400    NO FIELD DEFINED?
       BEQ    FLDI2    IF NO FIELD MARKERS
* MOVE ORIG CONTENTS TO SCREEN
FLDI1 LDA     ,U       LOOK AT DESTINATION POSITION
       CMPA   #$5B     LEFT BRACKET?
       BEQ    FLDI2    IF YES
       CMPA   #$5D     RIGHT BRACKET?
       BEQ    FLDI2    IF YES
       LDA    ,Y+
       STA    ,U+
       BRA    FLDI1
FLDI2 JSR     DERR     WAIT FOR A KEYSTROKE
       TFR    A,B
       LDU    6,S
       LDY    4,S
       CMPU   #$400    NO FIELD MARKERS?
       BEQ    FLDIXX   IF NO FIELD MARKERS, EXIT WITH KEY IN A & B
       CMPA   #$20     WAS IT LOW CONTROL KEY?
       BCS    FLDIX    IF YES
       CMPA   #$5B     SPL CHR/NUMBERS/UPPER CASE?
       BCS    FLDI4    IF YES
       CMPA   #$60     HIGH CONTROL CODES?
       BCS    FLDIX    IF YES
* FALL THRU WITH LOWER CASE
FLDI4 LDA     ,U
       CMPA   #$5B     IS CURSOR OVER START OF FIELD?
       BEQ    FLDIX    IF YES
       CMPA   #$5D     OVER END OF FIELD?
       BEQ    FLDIX    IF YES
       TFR    B,A
       STA    ,Y+      SAVE CHR IN INPUT AREA
       CMPA   #$40     SPL CHR?
       BCC    FLDI5    IF YES
       ORA    #$40
FLDI5 STA     ,U+
FLDI5A STY    4,S
       STU    6,S
       CLRB
       LDA    ,U
       CMPA   #$5D     FIELD OVERFLOW?
       BNE    FLDI2
*
* EXIT WITH LAST KEY PUSHED IN B (ZERO IF FIELD OVERFLOW)
FLDIX CMPA    #LEFT
       BNE    FLDIXX
       LDA    #$20
       STA    ,Y
       STA    ,U
       LDA    -1,U
       CMPA   #$5B     IN FIRST POSN NOW?
       BEQ    FLDIX1   IF YES
       LEAY   -1,Y
       LEAU   -1,U
FLDIX1 LDA     #$20
       STA    ,Y
       STA    ,U
       BRA    FLDI5A
FLDIXX RTS
*
*******************************************
* ACTUALLY LOAD AND EXECUTE PROGRAM
* GIVEN: DCB FOR THE PROGRAM FILE STORED
*        IN USRDCB
*******************************************
B12    FDB   B13-B12   SIZE OF OVERLAY
       PSHS X          SAVE MY BASE (LOWEST LOAD ADDRESS ALLOWED)
* STEP 1 OPEN THE PROGRAM FILE - DOES IT EXIST?
       LDU   #USRDCB
       LDA   #$FF
       STA   DCBDRV,U SEARCH ALL DRIVES
       DOS   OPEN,INPUT
       BEQ   EX1       IF OK
       CMPA #ERR13     NOT PREV CLOSED IS OK
       BEQ   EX1
EXERR JSR     [ERROR]
       PULS   X
       DOS    GO,MENU
*
* READ FILE PREFIX DATA (LOAD ADDR, RBA OF 1ST OVERLAY. ETC)
EX1    LDX    >OLYLOC POINT BEYOND ME
       STX    DCBLRB,U USE AS LOGICAL REC BUFFER
       LDD    #10      READ 1ST 10 BYTES OF PROGRAM FILE
       STD    DCBRSZ,U
       DOS    READ,RBA
       BNE    EXERR
       TST    ,X       IS 1ST BYTE ZERO?
       BEQ    EX2      IF YES, OK
       LDA    #ERR27   WRONG TYPE FILE
       BRA    EXERR
EX2    LDD    3,X      (LOAD ADDRESS)
       BEQ    EX3A     IF BASED AT ZERO, ASSUME RELOCATABLE
       CMPD   ,S       HE MUST LOAD ABOVE THIS POINT
       BCC    EX3      IF HE IS OK
       LDA    #ERR26   LOAD ADDR IS TOO LOW
       BRA    EXERR
* LOAD ADDRESS IS HIGH ENOUGH
EX3    STD    DCBLRB,U SET THIS AS LOGICAL RECORD BUFFER
EX3A   LDD    DCBLRB,U
       INCD
       STD    >USRBSE
       LDD    8,X      (SHOULD BE RBA OF 1ST OVERLAY)
       STD    DCBRSZ,U THAT IS ALSO HOW BIG ROOT SECTION IS
       ADDD   DCBLRB,U RESULT IS WHERE END OF ROOT WILL BE IN MEMORY
       ADDD   #3
       STD    >OLYLOC SET THIS AS BASE OF FUTURE OVERLAYS
       TFR    D,Y
       LDA    #$FF     INVALIDATE WHICH OVERLAY IS IN OVERLAY AREA
       STA    -1,Y
       LDA    #5
       STA    DCBRBA+2,U START READING WITH 6TH BYTE
       PULS   X        U
       JMP    B12A     GO LOAD ROOT & XFER CONTROL TO IT
*
************************************************************************
* RELOCATABLE REAL-TIME CLOCK ROUTINE
*
* DESIGNED TO BE LOADED BY MAINLINE OF USER'S PROGRAM, SAVING ITS
* LOAD ADDRESS. THEN ACCESSED THRU THE SAVED VECTOR TO PERFORM
* FUNCTIONS.
*
* GIVEN: B=0 - INITIAL CALL, LINK SELF INTO TIME INTERUPT AND PROTECT
*              MYSELF FROM BEING OVERLAYED
*        B=FF - UNLINK AND RELEASE OVERLAY SPACE
*        B=1 - GET TIME
*        B=2 - SET TIME
* WITH GET & SET TIME, Y CONTAINS SECONDS AND 60THS OF SECONDS
*                      U CONTAINS HOURS AND MINUTES
* WITH INITIAL CALL, U -> DISPLAY ADDRESS (0=NO DISPLAY DESIRED)
*                    Y = 1 FOR HOURS, 2 FOR MINUTES, 4 FOR SECONDS
*                        OR ANY COMBINATION (ADDED TOGETHER)
************************************************************************
B13    FDB    B14-B13 OVERLAY SIZE
CLK    EQU    B13      (TO ALLOW CHANGING TO DIFFERENT OVERLAY DURING DEVELOPMENT)
       BRA    CLK1     JUMP OVER LOCALS
HRS    FCB    0        HOURS (COUNTS TO 255(
MIN    FCB    0        MINUTES (ALL VALUES SET TO ZERO WHEN LOADED)
SEC    FCB    0        SECONDS
CNT    FCB    0
TMELOC FDB     0        TIME DISPLAY LOC
TMEOPT FCB     0        HR,MIN,SEC OPTION
CLK1 TSTB             WHICH OPTION?
       BEQ    CLKGO
       LEAX   -2,X
       TSTB
       BMI    CLKSTP
       DECB
       BEQ    CLKGET
CLKSET STU    HRS-CLK,X
       STY    SEC-CLK,X
       CLRA
       RTS
CLKGET LDU    HRS-CLK,X
       LDY    SEC-CLK,X
       CLRA
       RTS
*
CLKGO STU     TMELOC-CLK,X SAVE DISPLAY ADDRESS
       TFR    Y,D
       STB    TMEOPT-CLK,X SAVE DISPLAY OPTION
       LEAU   CLKTME-CLK,X POINT AT INTERVAL ROUTINE
       STX    4,U      SET LDX COMMAND TO LOAD CURRENT X VALUE
       DOS    TIME,ON PLUG IN THE CLOCK
       LDD    2,S      RET ADDR TO CALLER
       PSHS   D        PUT IN TOP OF STACK TO BYPASS NORMAL EXIT OF OVERLAY
       CLRA
       LEAX   2,X      TELL USER WHERE TO ENTER ME
       RTS             RETURN TO CALLER
*
CLKSTP LEAU   CLKTME-CLK,X POINT AT INTERVAL ROUTINE
       DOS    TIME,OFF PULL THE PLUG
       PULS   D        RET ADDR TO CALLER
       STD    2,S      SET TO RET TO HIM AFTER EXITING FROM OVERLAY
       CLRA
       RTS
 *
CLKTME JMP    >0
       LDX    #0       THIS INSTR MODIFIED BY ABOVE ROUTINE
       LDD    SEC-CLK,X LOAD SEC & 60THS
       INCB
       STD    SEC-CLK,X
       CMPB   #56      FULL SECOND?
       BCS    CLKTME   IF NO, EXIT
       CLRB
       ADDA   #1
       DAA
       STD    SEC-CLK,X
       CMPA   #$60     FULL MINUTE?
       BCS    CLKDSP   IF NO
       CLRA
       STA    SEC-CLK,X
       LDD    HRS-CLK,X
       ADDB   #1
       EXG    A,B
       DAA
       EXG    A,B
       STB    MIN-CLK,X
       CMPB   #$60     FULL HOUR?
       BCS    CLKDSP   IF NO
       CLRB
       ADDA   #1
       DAA
       STD    HRS-CLK,X
       BRA    CLKTME
* DISPLAY RESULTS IF NECESSARY
CLKDSP LDU    TMELOC-CLK,X DISPLAY LOC
       BEQ    CLKTME   EXIT
       LDB    TMEOPT-CLK,X DISPLAY OPTION
       LSRB
       BCC    CLK2     IF NO
       LDA    HRS-CLK,X
       BSR    CLKEDT
CLK2   LSRB            MINUTES DESIRED?
       BCC    CLK3     IF NO
       LDA    MIN-CLK,X
       BSR    CLKEDT
CLK3   LSRB            SECONDS DESIRED?
       BCC    CLKTME   IF NO
       LDA    SEC-CLK,X
       BSR    CLKEDT
       BRA    CLKTME
* EDIT THE BCD NUMBER IN A - DISPLAY AT U
CLKEDT PSHS   A
       LSRA
       LSRA
       LSRA
       LSRA
       ADDA   #$30
       STA    ,U+
       PULS   A
       ANDA   #$0F
       ADDA   #$30
       STA    ,U++
       RTS
*
********************************************************************
* DOS MAIN MENU DISPLAY
********************************************************************
B14    FDB    B15-B14 SIZE OF OVERLAY
* DISPLAY DOS MENU SCREEN
       LDD    #100     STARTING LINE NUMBER
       LDY    #199     END OF RANGE
       LDU    #0       SAY CLEAR SCREEN FIRST
       JSR    DOMAP    DISPLAY MENU MAP
MENU1  SYSTEM POLCAT
       BEQ    MENU1
       SUBA   #$31     LESS THAN 1?
       BEQ    MENU2    IF 1 ENTERED (RET TO BASIC)
       BCS    MENU1    IF YES
       CMPA   #6       NUMBER OF MENU SELECTIONS THAT HAVE BEEN WRITTEN
       BCC    MENU1    IF NOT IN RANGE
       INCA            TO GET OVERLAY NUMBER OF SERVICE ROUTINE
       JSR   [GO]      PAGE IT IN & GO TO IT
MENU2  JMP    OBASIC
*
**************************************************************
* BUFFERED PRINT I/O OVERLAY
*
* TO ACTIVATE:
*              LDU #SIZE (TOTAL MEMORY TO USE FOR THIS PURPOSE)
*              DOS DO,BUFPRT
*
* TO USE:
*         LDA CHARACTER TO PRINT
*   AGAIN CLRB (SAYS "I AM NOT SHUTTING DOWN")
*         JSR [PRNT]
*         BNE AGAIN IF BUFFER WAS FULL, TRY AGAIN (OR GO DISPLAY MSG)
*
* TO TERMINATE:
*               LDB #1 (ANY NON-ZERO SAYS SHUT DOWN)
*               JSR [PRNT]
**************************************************************

B15    FDB    B16-B15 SIZE OF OVERLAY
BP     EQU    B15      (FOR USE IN RELATIVE ADDRESSING
       BRA    BP1      JUMP OVER LOCALS
PRTBUF FDB    0        POINTER TO PRINT BUFFER
BUFSZ FDB     0        SIZE OF PRINT BUFFER
BUFCNT FDB    0        NUMBER OF CHRS IN BUFFER
SNDCHR FDB    0        POINTER INTO BUFFER FOR CHR BEING SENT
STRCHR FDB    0        POINTER INTO BUFFER FOR CHR BEING STORED
PRNTSV FDB    0        SAVE AREA FOR VECTOR TO ORIG PRNT ROUTINE
*
* SEE IF ENOUGH ROOM PROVIDED
BP1    TFR    U,D      PUT SPACE ALLOWED IN D
       SUBD   #BPSZ+5 AMOUNT NOT AVAILABLE FOR BUFFER
       BCC    BP1A     IF ROOM FOR AT LEAST 1 BYTE BUFFER
       LDA    #ERR24   BUFFER NOT BIG ENOUGH
       RTS
* SET UP FOR BUFFERED PRINTING
BP1A   ADDD   #1       (ACTUAL SIZE OF BUFFER)
       STD    BUFSZ-BP,X SAVE BUFFER SZ
       LEAY   BPSZ+3,X POINT AT BASE OF BUFFER
       STY    PRTBUF-BP,X SAVE IT
       LEAY   D,Y      POINT BEYOND END OF BUFFER
       CLR    ,Y+ SAY SAY NO VALID OVERLAY FOLLOWS
       STY    >OLYLOC THIS IS WHERE NEXT OVERLAY GOES
       STX    BPTME+4-BP,X MODIFY LDX COMMAND
       STX    BPOUT+3-BP,X (SO IT KNOWS WHERE LOCAL WS IS)
       LEAU   BPTME-BP,X POINT AT TIME ROUTINE
       DOS    TIME,ON   PLUG IT IN
       LDU    >PRNT    GET ADDR OF ORIGINAL PRINT ROUTINE
       STU    PRNTSV-BP,X SAVE IT
       LEAU   BPOUT-BP,X POINT AT ENTRY FOR BUFFERED PRINT
       STU    >PRNT
       LDU    2,S      RET ADR TO USER
       PSHS   U        (BYPASS NORMAL RETURN THRU UN-DO)
       CLRA            SAY DONE OK
       RTS
*
* SEND A CHARACTER TO THE PRINTER VIA BUFFERED I/O
BPOUT PSHS    A,X,U
       LDX    #0       (THIS INSTR MODIFIED BY SETUP LOGIC)
       TSTB            REQUEST TO SHUT DOWN?
       BNE    BPO3
BPO1   LDD    BUFCNT-BP,X
       CMPD   BUFSZ-BP,X ROOM FOR MORE?
       BCS    BPO1A    IF ROOM
       LDA    #1       SET NON-Z COND
       PULS   A,X,U
       BCC    BPO1     IF NO ROOM
BPO1A DSABLI
       LDU    PRTBUF-BP,X
       LDD    STRCHR-BP,X DISPLACEMENT IN BUFFER
       LEAU   D,U      POINT AT NEXT STORE POSITION
       ADDD   #1
       CMPD   BUFSZ-BP,X WRAP AROUND?
       BCS    BPO2     IF NO
       CLRD
BPO2   STD    STRCHR-BP,X
       LDA    ,S       (CHR TO BE PRINTED)
       STA    ,U
       LDD    BUFCNT-BP,X
       ADDD   #1
       STD    BUFCNT-BP,X
       ENABLI
       PULS   A,X,U,PC
* WAIT FOR BUFFER TO EMPTY
BPO3   LDD    BUFCNT-BP,X EMPTY YET?
       BNE    BPO3      IF NO WAIT
       LEAU   BPTME-BP,X POINT AT TIME ROUTINE
       DOS    TIME,OFF UN PLUG IT
       LDD    PRNTSV-BP,X GET ADDR OF ORIG DRIVER
       STD    >PRNT     RESTORE IT
       LDD    PRTBUF-BP,X WHERE NEXT OVERLAY SHOULD HAVE GONE
       STD    >OLYLOC
       PULS   U         (RET ADDR)
       STD    2,S       I'M SET TO RETURN VIA UN-DO)
       RTS
*
* TIME INTERVAL DRIVEN PRINT LOGIC
BPTME  JMP    >0       (TO NEXT TIME ROUTINE)
       LDX    #0       (INSTRUCTION MODIFIED BY ABOVE LOGIC)
* IS THERE DATA IN THE BUFFER TO BE SENT TO PRINTER?
       LDD    BUFCNT-BP,X
       BEQ    BPTME    IF NO, EXIT
* TRY TO SEND IT IT (PRINTER MIGHT NOT BE READY)
       LDU    PRTBUF-BP,X POINT AT BUFFER
       LDD    SNDCHR-BP,X DISPLACEMENT WITHIN BUFFER
       LDA    D,U      GET CHR OUT OF BUFFER
       JSR    [PRNTSV-BP,X]
       BNE    BPTME    IF PRINTER WAS NOT READY
* ADVANCE BUFFER POINTER
       LDD    SNDCHR-BP,X
       ADDD   #1
       CMPD   BUFSZ-BP,X IS POINTER WRAPPING AROUND END OF BUFFER?
       BCS    BPT1     IF NO
       CLRD
BPT1   STD    SNDCHR-BP,X SAVE POINTER TO NEXT CHR
* ADJUST BUFFER COUNT
       LDD    BUFCNT-BP,X
       SUBD   #1
       STD    BUFCNT-BP,X
       BRA    BPTME    EXIT (ONLY SEND ONE CHR PER INTERUPT!)
*
*********************************
* BUFFERED KEYBOARD INPUT OVERLAY
*********************************
B16    FDB    B17-B16
BPSZ   EQU    B16-B15 (FOR PREVIOUS ROUTINE'S USE)
BK     EQU    B16
       BRA    BK1      JUMP OVER LOCALS
KEYBUF FDB    0        ADDR OF KEYBOARD BUFFER
KEYSZ FDB     0        SIZE OF KBD BUFFER
KEYCNT FDB    0        NUMBER OF KEYSTROKES IN BUFFER
SNDKEY FDB    0        DISPLACEMENT TO NEXT KEY TO GIVE USER
STRKEY FDB    0        DISPLACEMENT FOR STORING NEXT KEYSTROKE
KEYSV FDB     0        SAVE AREA FOR ADDR OF ORIGINAL KBD ROUTINE
*
* SET UP FOR BUFFERED KBD
BK1    TFR    U,D      PUT SPACE ALLOWED IN D
       SUBD   #BKSZ+5 AMOUNT NOT AVAILABLE FOR BUFFER
       BCC    BK1A     IF ROOM FOR AT LEAST 1 BYTE BUFFER
       LDA    #ERR28   BUFFER NOT BIG ENOUGH
       RTS
BK1A   ADDD   #1       (ACTUAL SIZE OF BUFFER)
       STD    KEYSZ-BK,X SAVE BUF SZ
       LEAY   BKSZ+3,X POINT AT BASE OF BUFFER
       STY    KEYBUF-BK,X
       LEAY   D,Y
       CLR    ,Y+       SAV NO VALID OVERLAY FOLLOWS
       STY    >OLYLOC NEXT OVERLAY GOES HERE
       STX    BKTME+4-BK,X MODIFY LOX INSTR
       STX    BKGIVE+3-BK,X DITTO
       LEAU   BKTME-BK,X
       DOS    TIME,ON PLUG IN TIME RTN
       LDU    >KEYIN
       STU    KEYSV-BK,X
       LEAU   BKGIVE-BK,X
       STU    >KEYIN
       LDU    2,S
       PSHS   U
       CLRA
       RTS
*
* POLL FOR A CHARACTER TO GIVE USER
BKGIVE PSHS   B,X,U
       LDX    #0       (THIS INSTRUCTION MODIFIED BY SETUP)
       LDD    KEYCNT-BK,X COUNT OF BUFFERED CHRS
       BNE    BKG1     IF ONE TO SEND
       PULS   B,X,U,PC IF NONE, EXIT WITH A=ZERO
BKG1   LDU    KEYBUF-BK,X ADDR OF BUFFER
       LDD    SNDKEY-BK,X DISPLACEMENT
       LEAU   D,U      POINT AT CHARACTER
* ADJUST POINTER TO NEXT POSITION
       ADDD   #1
       CMPD   KEYSZ-BK,X WRAP AROUND?
       BCS    BKG1     IF NO
       CLRD
BKG2   STD    SNDKEY-BK,X
       LDA    ,U
       PSHS   A
       LDD    KEYCNT-BK,X
       SUBD   #1
       STD    KEYCNT-BK,X
       TST    ,S
       PULS   D,X,U,PC
*
* TIME INTERVAL KEYBOARD SCAN ROUTINE
BKTME JMP     >0       TO NEXT TIME ROUTINE
       LDX    #0       (MODIFIED BY SETUP)
BKTMEA LDD    KEYCNT-BK,X
       CMPD   KEYSZ-BK,X IS BUFFER FULL?
       BCS    BKT1     IF NO
* BUFFER IS FULL - GO BEEP
       LDX    #U4BDR
       LDA    ,X
       EORA   #2       COMPLIMENT SOUND BIT
       STA    ,X
       LDY    #$20     PULSE WIDTH
BKT0   LEAY   -1,Y
       BNE    BKT0
       BRA    BKTME    EXIT
BKT1   JSR    [KEYSV-BK,X] GO POLL KEYBOARD
       TSTA
       BEQ    BKTME    IF NO NEW KEYSTROKES, EXIT
       PSHS   A        SAVE KEY
       LDU    KEYBUF-BK,X
       LDD    STRKEY-BK,X DISPLACEMENT TO SAVE LOC
       LEAU   D,U      POINT AT SAVE LOC
       ADDD   #1       POINT TO NEXT SAVE LOC
       CMPD   KEYSZ-BK,X WRAP AROUND?
       BCS    BKT2     IF NO
       CLRD
BKT2   STD    STRKEY-BK,X
       LDD    KEYCNT-BK,X
       ADDD   #1
       STD    KEYCNT-BK,X
       PULS   A
       STA    ,U
       BRA    BKTMEA   GO CHECK FOR ANOTHER KEY DOWN
*
************************************************************
* COPY FILE OVERLAY
* GIVEN: B (BIT 0) = ZERO IF NO DISK SWAPPING, 1 IF SWAPPING
*        U-> SOURCE FILE DCB (UNOPENED)
*        Y-> DEST FILE DCB (UNOPENED)
* USES MEMORY FROM "OLYLOC" TO "MAXMEM"
* USES LAST LINE ON SCREEN FOR PROMPTS IF SWAPPING DISKETTES
************************************************************
B17    FDB    B18-B17
       PSHS   D,X,Y,U
       LEAS   -6,S
       BRA    B17A
* ,S COUNT OF SECTORS IN MEMORY
* 1,S EOF SW
* 2,S=NEXT INPUT PRN
* 4,S=NEXT OUTPUT PRN
* 6,S=PGS AVAIL
* 7,S=SWAP SW
* 8,S=BASE
* 10,S=DEST DCB ADDR
* 12,S=SOURCE DCB ADDR
* 14,S=RET ADDR
B17M1 FCC      /LOAD SOURCE DISKETTE            /
B17M2 FCC      /LOAD DESTINATION DISKETTE       /
B17M3 FCC      /LOAD  S Y S T E M  DISKETTE     /
*
* SETUP STACK
B17A   ANDB    #1 SET TO 1 OR 0
       LDA     DCBDRV,U
       CMPA    DCBDRV,Y SAME DRIVE?
       BEQ     B17B     IF YES
       CLRB
B17B   STB     7,S
       CLRA
       CLRB
       STD     ,S
       STD     2,S      STARTING INPUT PRN
       STD     4,S      STARTING OUTPUT PRN
       LDD     >MAXMEM
       SUBD    >OLYLOC HOW MUCH MEM TO WORK WITH
       BCS     B17B1    IF NOT ENOUGH
       TSTA
       BNE     B17C     IF AT LEAST 1 PAGE
B17B1 LDA      #ERR29   NOT ENOUGH MEM
*
* COMMON EXIT
B17X   STA    6,S
       TST    7,S
       BEQ    B17XIT
* RECOVER SYSTEM DISKETTE
       LDX    8,S
       LEAX   B17M3-B17,X
       BSR    B17WTE
       LDU    #MSGDCB
       DOS    OPEN,INPUT TO RE-LOAD FAT TABLE
B17XIT LEAS   6,S
       PULS   D,X,Y,U,PC
*
* DISPLAY FLASHING MSG & WAIT FOR DISKETTE SWAP
B17WTE LDY    #$400+512-32 (LAST LINE)
       LDB    #32
B17WT1 LDA    ,X+
       STA    ,Y+
       DECB
       BNE    B17WT1
       CLR    >CLOCK+1
B17WT2 SYSTEM POLCAT   WAIT FOR KEYSTROKE
       CMPA   #$0D
       BEQ     B17WTX
       LDX     #$400+512-32
       LDA     >CLOCK+1
       ANDA    #$20
       LSLA
       PSHS    A
       LDB     #32
B17WT3 LDA     ,X
       ANDA    #%10111111
       ORA     ,S
       STA     ,X+
       DECB
       BNE     B17WT3
       PULS    A
       BRA     B17WT2
B17WTX RTS
*
B17C   STA    6,S PAGES AVAILABLE
*
* LOOP TO COPY FILE
B17D   LDU    12,S     SOURCE
       LDD    >OLYLOC
       STD    DCBBUF,U
       TST    7,S      SWAPPING?
       BEQ    B17D0    IF NO
* WAIT FOR SOURCE DISKETTE
       LDX    8,S
       LEAX   B17M1-B17,X
       BSR    B17WTE
B17D0 DOS     OPEN,INPUT
       BNE    B17X     IF NOT FOUND
       LDD    2,S
       STD    DCBPRN,U SET STARTING SECTOR NUMBER
       BNE    B17E     IF NOT FIRST TIME
* FIRST TIME - SAVE DIRECTORY DATA IN OUTPUT DCB
       LDY    10,S
       LEAU   11,U
       LEAY   11,Y     EXCEPT FOR NAME
       LDB    #32-11
B17D1 LDA     ,U+
       STA    ,Y+
       DECB
       BNE    B17D1
       LDU    12,S     SOURCE
B17E   CLR    ,S       SECTORS IN MEMORY
*
* LOAD LOOP
B17F   JSR    CSENT    XLATE PRN INTO TRACK & SECTOR
      BNE    B17F1    IF OUT OF RANGE
      JSR    DSKRED   DO PHYSICAL I/O
      BNE    B17XX    IF I/O ERR
      LDD    DCBPRN,U
      ADDD   #1
      STD    DCBPRN,U
      INC    DCBBUF,U
      INC    ,S       COUNT SECTORS READ
      LDB    ,S
      CMPB   6,S      IS BUFFER FULL
       BNE     B17F    IF NO
       BRA     B17G    GO WRITE IT
B17XX LBRA     B17X    THIS STMT USED AS AN UP-LINK
*
* INPUT AT END - SET EOF SW
B17F1  INC     1,S
*
* CLOSE INPUT
B17G   LDD     DCBPRN,U
       STD     2,S      SAVE FOR NEXT BATCH
       DOS     CLOSE,IT
       LDA     ,S       ANY SECTORS READ?
       BEQ     B17XX    IF NO, I'M DONE
*
* OPEN OUTPUT
       TST     7,S      SWAPPING?
       BEQ     B17H     IF NO
       LDX     8,S
       LEAX    B17M2-B17,X
       LBSR    B17WTE   WAIT FOR DESTINATION DISKETTE
B17H   LDU     10,S     OUTPUT FILE DCB
       LDD     >OLYLOC START OF BUFFER
       STD     DCBBUF,U
       DOS     OPEN,OUTPUT+FAST
       BEQ     B17H1    IF FILE EXISTS
       CMPA    #12
       BEQ     B17H2    IF CREATED
       BRA     B17XX    IF OTHER ERROR
*
* FILE EXISTS
B17H1 LDD      4,S
       BNE     B17I     IF NOT FIRST TIME• ITS OK
       DOS     CLOSE,IT
       LDA     #ERR30
       BRA     B17XX
*
* FILE CREATED
B17H2  LDD     4,S
       BEQ     B17I     IF FIRST TIME, OK
       LDA     #ERR31   MISC ERR
       BRA     B17XX
*
B17I   STD     DCBPRN,U
*
* WRITE LOOP
B17J   JSR     CSENT    XLATE PRN INTO TRACK & SECTOR
       BNE     B17XX
       JSR     DSKWRT   WRITE SECTOR
       LBNE    B17X
       LDD     DCBPRN,U
       ADDD    #1
       STD     DCBPRN,U
       INC     DCBBUF,U
       DEC     ,S       COUNT DOWN SECTORS WRITTEN
       BNE     B17J
*
* CLOSE INPUT
       LDD     DCBPRN,U
      STD    4,S      SAVE FOR NEXT BATCH
      SUBD   #1
      STD    DCBMRB,U
      LDX    12,S     SOURCE DCB
      LDD    DCBNLS,X
      STD    DCBNLS,U
      STB    DCBMRB+2,U
      DOS    CLOSE,IT
      CLRA
      TST    1,S      AT EOF?
      LBNE   B17XX    I'M DONE
      LBRA   B17D     GO COPY ANOTHER BATCH OF SECTORS
*
**************************
* GET MULTIPLE USER INPUTS
* GIVEN B=NUMBER OF INPUTS
**************************
B18    FDB    B19-B18
INPTS EQU     18
       LDA    #1
       PSHS   D
B18B   LDU    #$400
       LDB    ,S
B18C   LDA    ,U+
       CMPA   #$5B
       BEQ    B18D
       CMPU   #$600
       BCS    B18C
       LDU    #$401
B18D   DECB
       BNE    B18C
* INPUT A FIELD
       CLR    CLOCK+1
       LEAX   -1,U
B18E   LDB    CLOCK+1
       ANDB   #16
       BEQ    B18E1
       LDA    #$5B
       BRA    B18E2
B18E1 LDA     #$1B
B18E2 STA     ,X
       PSHS   X,U
       SYSTEM POLCAT
       PULS   X,U
       TSTA
       BEQ    B18E
       CMPA   #BREAK
       BEQ    B18X
       CMPA   #DOWN
       BEQ    B18F
       CMPA   #UP
       BEQ    B18G
       CMPA   #ENTER
       BEQ    B18X
       CMPA   #LEFT
       BEQ    B18I
       CMPA   #$20
       BCS    B18E
       CMPA   #$5B
       BCS    B1BH
       CMPA   #$60
       BCS    B1BH
       BRA    B18E
* DOWN
B18F   LDA    ,S
       CMPA   1,S
       BCC    B18G1    IF AT END ALREADY
       INCA
       STA    ,S
       BRA    B18G1
* UP
B18G   LDA    ,S
       CMPA   #1
       BEQ    B18G1
       DECA
       STA    ,S
B18G1 LDA     #$5B
       STA    ,X
       BRA    B18B
* TEXT CHR
B1BH   ORA    #$40
       STA    ,U+
       LDA    ,U
       CMPA   #$5D
       BEQ    B18F
       BRA    B18E
* BACK ARROW
B18I   LDA    ,-U
       ANDA   #$BF
       CMPA   #$1B
       BNE    B18E
       LDA    ,U+
     ; BRA    B18I      KJF: Changing this to match the binary DOS.BIN that
     ;                       shipped with Disk EDTASM, as it appears to be a fix
     ;                       for a potentially infinite loop.
       BRA    B18E
* BREAK OR ENTER
B18X   TFR    A,B
       LEAS   2,S
       LDA    #$5B
       STA    ,X
       RTS
*
***********************************
* SCAN FOR SELECTED
***********************************
B19    FDB    B20-B19
SCNDIR EQU    19
       LDX    $C006    PARAMETER AREA
       LDA    #2       READ
       STA    ,X+
       LDA    ,U       DRIVE
       STA    ,X+
       LDD    #$1103   TRACK & SECTOR
       STD    ,X+      LEAVE X -> SECTOR
       LDY    #SYSBUF
       STY    1,X
       LDA    1,U      STARTING OCCURANCE
B19A   CMPA   #72      ANY MORE ON THIS DRIVE?
       BCC    B19NO
B19B   SUBA   #8
       BCS    B19C     IF IN THIS SECTOR
       INC    ,X
       BRA    B19B
B19C   ADDA   #8
       BEQ    B19D
       LDB    #32
       MUL             DISPLACEMENT IN THIS SECTOR
       LEAY   D,Y      OFFSET TO 1ST ENT TO SCAN
       BRA    B19D1
B19D   PSHS   X,Y,U
       JSR    [$C004]
       PULS   X,Y,U
       LDA    3,X      RESULT
       BNE    B19NO    IF I/O ERR
* COMPARE AGAINST ARGUMENT
* REGISTERS:X->SECTOR NBR
*           Y->ENTRY IN BUFFER
*           U->SEARCH ARGUMENT
B19D1 PSHS    Y,U
       LDB    #11      BYTES TO COMPARE
       LEAU   2,U      TO START OF ARGUMENT
       LDA    ,Y
       BEQ    B19E1    IF EMPTY ENTRY
       BMI    B19E1    IF END OF DIRECTORY
B19E   LDA    ,U+
       CMPA   #'*      WILDCARD?
       BEQ    B19F
       CMPA   ,Y+
       BEQ    B19G
* NO MATCH
B19E1 PULS    Y,U
       INC    1,U
       LDA    1,U
       CMPA   #72      ANY MORE?
       BCC    B19NO
       LEAY   32,Y     POINT AT NEXT ENTRY
       CMPY   #SYSBUF+256
       BCS    B19D1
* READ NEXT SECTOR
       LDY    #SYSBUF
       INC    ,X
       BRA    B19D
B19F   LDA    ,Y+      BYPASS SOURCE CHR
B19G   DECB
       BNE    B19E
* MATCH FOUND
       PULS   Y,U
       INC    1,U      SEARCH CONTINUES WITH NEXT ENTRY
       LEAU   2+11,U
       LDB    #32
B19H   LDA    ,Y+
       STA    ,U+
       DECB
       BNE    B19H
       RTS
B19NO LDA     #$FF
       STA    1,U      SAY NO MORE
       RTS
*
; B20     RMB    1    KJF: Changing to FCBs so that a 0 is output, to match the 
; B21     RMB    1         shipping version of DOS.BIN.
B20     FCB    0
B21     FCB    0
*
        OPT    L
; LASTPG  RMB    1    KJF: Change to EQU to make sure no extra bytes get generated,    
;                          to match the shipping version of DOS.BIN.
LASTPG  ZMB    1      END OF OVERLAYS
; LASTPG  EQU    *      
                    
B22     EQU    LASTPG
BKSZ    EQU    B17-B16
PGMSZ   EQU    OVRLAY-ORGIN-1
TOTSZ   EQU    LASTPG-ORGIN-1
START   EQU    DOS      START OF DISK FILE
END     EQU    LASTPG+DOS-ORGIN END OF DISK FILE
ENTRY   EQU    OVRLAY   INITIAL ENTRY POINT INTO PROGRAM
LOWUSR  EQU     OVRLAY+3 LOWEST POINT WHERE USER PGM CAN LOAD
FIXIT   EQU     $1E00-LASTPG+ORGIN POINT THAT BASIC CLOBBERS
        TTL    DOS - CROSS REFERENCE

        ; KJF: Skip the relocation logic when running stand-alone.
        END    InitWithoutRelocation

    ENDC   ; SKIP_OVERLAY_SECTION
